# REL module configuration (the module list itself is the `modules:` block of config.yml; the
# per-module splits/symbols/sym_map/rel.json under config/G4BE08/modules/<mod>/ are generated by
# tools/gen_rel_config.py). Every unit is compiled and linked; a unit listed in NON_MATCHING is
# linked from the split original object instead. Per-unit notes: docs/unit-notes.md.

# Unit boundaries per module: list of (unit name, first function or .text offset[, source file under src/]). The debug
# build's Bio4.<mod>.sym has no per-object information, so a module is one unit "<mod>/<mod>.cpp"
# unless listed here. Data sections are attributed to units by the relocations from the unit's code
# (see the tool). A third element names a source shared by several modules (the same object is
# linked into each of them).
#
# Every st2_* module ends with the same st2.cpp object (__FILE__ "D:/Bio4/Prog/st2.cpp": set/setTbl
# register all stage-2 room Init/Main pairs in St2_data_tbl, then the SN REL entry points _prolog
# (ctors, setTbl), _epilog (dtors) and _unresolved (HALT)). st1_*/st4_0 have st1.cpp/st4.cpp the same way.
_ST2 = ("st2.cpp", "set", "st2/st2.cpp")
_ST1 = ("st1.cpp", "set", "st1/st1.cpp")
_ST4 = ("st4.cpp", "set", "st4/st4.cpp")
# Stage modules: every REL starts with the module's copy of em_wrap.cpp (cEmControl/cEmPatrol/cEmGuard,
# the cEmWrap enemy handle with its ~50 in-class members, the free setEm/SceCkFindPL; no __FILE__ string;
# src/st/em_wrap.cpp). The original REL link dead-stripped it at function level like the DOL: only the
# members the module's rooms (transitively) call survive, in declaration order, while every string and
# constant pool stays (.rodata 0..0xAE8 in all modules; st2_4/st4_0 were built with a later revision
# without the "cEmControl::SetPatrol" message, src/st/em_wrap_v2.cpp, 0xAC4). st1_0 uses none of it
# (.text empty, strings only). st2_0/st2_3/st4_0 then carry cSceObj.cpp (D:/Bio4/Prog/cSceObj.cpp,
# stripped the same way: st2_0 lacks the *Move1_ang/*Move3_y/setStart members). Then one object per room
# (D:/Bio4/Prog/rNNN.cpp; sources under src/st1/, src/st2/, src/st4/ because r102/r103/r108 are the same
# object in st1_1 and st1_3), then st1.cpp/st2.cpp/st4.cpp. Room .rodata starts are pinned at the room's
# first header string (cFlag.set()/atari.h/event.h/map_obj.h..., emitted at parse time, never referenced).
UNITS = {
    # Weapon RELs (wepXX): the player routine object of the weapon class (shared by every module of
    # that class: src/wep/pl_<class>.cpp, `PlXxxMove` + the r2/r3 routines + the named
    # cManager<cLight> countActiveWork/create(int) copies), then the module's own object
    # (WepXX_init, the cObjXxx class, ObjXxx_init, _prolog/_epilog/_unresolved, nameless cLight block,
    # cObj createBack, cUnit copies). Some modules put the weapon class in its own object before the
    # routines (objXxx.cpp). Every object's .rodata starts with its own [cFlag.set()][atari.h][light.h]
    # header strings (unreferenced, hence the pins). Real file names are not in the binary.
    # pl0a (Krauser): the shotgun player routines in Krauser's build (no PlShotgunMove / reload; the
    # weapon modules' pl_shotgun object with fewer functions), then pl_klauser.cpp. Both objects start
    # with their own [cFlag.set()][atari.h][light.h] header strings (pl_klauser adds dmg.h).
    "pl0a": [
        ("pl0a/wep07.cpp", None, None),
        ("pl0a/pl_klauser.cpp", "setTexRender", None, {".rodata": 0x150, ".data": 0x30, ".bss": 0x0}),
    ],
    # pl0d (Wesker): the wep02 module's objects rebuilt for the player module (the cObjRuger class object
    # without ObjRuger_init, the handgun routines without PlHandgunMove) then pl_wesker.cpp. Each object
    # starts with its own header strings ([cFlag.set()][atari.h] / [..][light.h]).
    "pl0d": [
        ("pl0d/objRuger.cpp", None, None),
        ("pl0d/wep02.cpp", "wep02_r2_ready", None, {".rodata": 0x190, ".data": 0x0}),
        ("pl0d/pl_wesker.cpp", "testJacketSetWesker", None, {".rodata": 0x358, ".data": 0x58, ".bss": 0x0}),
    ],
    "wep13": [
        ("wep13/pl_rocket.cpp", None, "wep/pl_rocket.cpp"),
        ("wep13/wep13.cpp", "Wep13_init", None, {".rodata": 0x1BC}),
    ],
    "wep01": [
        ("wep01/objFn57.cpp", None),
        ("wep01/pl_handgun.cpp", "PlHandgunMove", "wep/pl_handgun.cpp", {".rodata": 0x198}),
        ("wep01/wep01.cpp", "Wep01_init", None, {".rodata": 0x360}),
    ],
    "wep02": [
        ("wep02/objMauser.cpp", None),
        ("wep02/objRuger.cpp", "ObjRuger_init", "wep/objRuger.cpp", {".rodata": 0x1d0}),
        ("wep02/pl_handgun.cpp", "PlHandgunMove", "wep/pl_handgun.cpp", {".rodata": 0x360}),
        ("wep02/wep02.cpp", "Wep02_init", None, {".rodata": 0x528}),
    ],
    "wep04": [
        ("wep04/pl_handgun.cpp", None, "wep/pl_handgun.cpp"),
        ("wep04/wep04.cpp", "Wep04_init", None, {".rodata": 0x1c8}),
    ],
    "wep05": [
        ("wep05/objCivilian.cpp", None),
        ("wep05/pl_handgun.cpp", "PlHandgunMove", "wep/pl_handgun.cpp", {".rodata": 0x170}),
        ("wep05/wep05.cpp", "Wep05_init", None, {".rodata": 0x338}),
    ],
    "wep06": [
        ("wep06/pl_handgun.cpp", None, "wep/pl_handgun.cpp"),
        ("wep06/wep06.cpp", "Wep06_init", None, {".rodata": 0x1c8}),
    ],
    "wep07": [
        ("wep07/pl_shotgun.cpp", None, "wep/pl_shotgun.cpp"),
        ("wep07/wep07.cpp", "Wep07_init", None, {".rodata": 0x1f8}),
    ],
    "wep08": [
        ("wep08/pl_shotgun.cpp", None, "wep/pl_shotgun.cpp"),
        ("wep08/wep08.cpp", "Wep08_init", None, {".rodata": 0x1f8}),
    ],
    "wep09": [
        ("wep09/objSniper.cpp", None),
        ("wep09/pl_rifle.cpp", "PlRifleMove", "wep/pl_rifle.cpp", {".rodata": 0x190}),
        ("wep09/wep09.cpp", "Wep09_init", None, {".rodata": 0x338}),
    ],
    "wep10": [
        ("wep10/objHkSniper.cpp", None),
        ("wep10/pl_rifle.cpp", "PlRifleMove", "wep/pl_rifle.cpp", {".rodata": 0x160}),
        ("wep10/wep10.cpp", "Wep10_init", None, {".rodata": 0x308}),
    ],
    "wep11": [
        ("wep11/objMachinegun.cpp", None, "wep/objMachinegun.cpp"),
        ("wep11/pl_machine.cpp", "PlMachineMove", "wep/pl_machine.cpp", {".rodata": 0x1b8}),
        ("wep11/wep11.cpp", "Wep11_init", None, {".rodata": 0x334}),
    ],
    "wep12": [
        ("wep12/objTompson.cpp", None),
        ("wep12/pl_machine.cpp", "PlMachineMove", "wep/pl_machine.cpp", {".rodata": 0x188}),
        ("wep12/wep12.cpp", "Wep12_init", None, {".rodata": 0x304}),
    ],
    "wep14": [
        ("wep14/objMine.cpp", None),
        ("wep14/wep14.cpp", "Wep14_init", None, {".rodata": 0x208}),
    ],
    "wep15": [
        ("wep15/pl_handgun.cpp", None, "wep/pl_handgun.cpp"),
        ("wep15/wep15.cpp", "Wep15_init", None, {".rodata": 0x1c8}),
    ],
    "wep16": [
        ("wep16/pl_knife.cpp", None, "wep/pl_knife.cpp"),
        ("wep16/wep16.cpp", "Wep16_init", None, {".rodata": 0x1d8}),
    ],
    "wep17": [
        ("wep17/objVp70.cpp", None),
        ("wep17/wep17.cpp", "Wep17_init", None, {".rodata": 0x190}),
    ],
    "wep19": [
        ("wep19/pl_grenade.cpp", None, "wep/pl_grenade.cpp"),
        ("wep19/wep19.cpp", "Wep19_init", None, {".rodata": 0x298}),
    ],
    "wep26": [
        ("wep26/pl_knife.cpp", None, "wep/pl_knife.cpp"),
        ("wep26/wep26.cpp", "Wep26_init", None, {".rodata": 0x1d8}),
    ],
    "wep27": [
        ("wep27/pl_machine.cpp", None, "wep/pl_machine.cpp"),
        ("wep27/wep27.cpp", "Wep27_init", None, {".rodata": 0x180}),
    ],
    "wep28": [
        ("wep28/pl_bow.cpp", None, "wep/pl_bow.cpp"),
        ("wep28/wep28.cpp", "Wep28_init", None, {".rodata": 0x190}),
    ],
    "wep29": [
        ("wep29/objMachinegun.cpp", None, "wep/objMachinegun.cpp"),
        ("wep29/pl_machine.cpp", "PlMachineMove", "wep/pl_machine.cpp", {".rodata": 0x1b8}),
        ("wep29/wep29.cpp", "Wep29_init", None, {".rodata": 0x334}),
    ],
    "wep30": [
        ("wep30/pl_grenade.cpp", None, "wep/pl_grenade.cpp"),
        ("wep30/wep30.cpp", "Wep30_init", None, {".rodata": 0x298}),
    ],
    "wep33": [
        ("wep33/pl_shotgun.cpp", None, "wep/pl_shotgun.cpp"),
        ("wep33/wep33.cpp", "Wep33_init", None, {".rodata": 0x1f8}),
    ],
    "wep38": [
        ("wep38/pl_handgun.cpp", None, "wep/pl_handgun.cpp"),
        ("wep38/wep38.cpp", "Wep38_init", None, {".rodata": 0x1c8}),
    ],
    "wep39": [
        ("wep39/pl_machine.cpp", None, "wep/pl_machine.cpp"),
        ("wep39/wep39.cpp", "Wep39_init", None, {".rodata": 0x180}),
    ],
    "wep40": [
        ("wep40/pl_rifle.cpp", None, "wep/pl_rifle.cpp"),
        ("wep40/wep40.cpp", "Wep40_init", None, {".rodata": 0x1a8}),
    ],
    "wep41": [
        ("wep41/pl_grenade.cpp", None, "wep/pl_grenade.cpp"),
        ("wep41/wep41.cpp", "Wep41_init", None, {".rodata": 0x298}),
    ],
    "wep42": [
        ("wep42/pl_grenade.cpp", None, "wep/pl_grenade.cpp"),
        ("wep42/wep42.cpp", "Wep42_init", None, {".rodata": 0x298}),
    ],
    "wep43": [
        ("wep43/objRuger.cpp", None, "wep/objRuger.cpp"),
        ("wep43/pl_handgun.cpp", "PlHandgunMove", "wep/pl_handgun.cpp", {".rodata": 0x190}),
        ("wep43/wep43.cpp", "Wep43_init", None, {".rodata": 0x358}),
    ],
    "wep44": [
        ("wep44/pl_handgun.cpp", None, "wep/pl_handgun.cpp"),
        ("wep44/wep44.cpp", "Wep44_init", None, {".rodata": 0x1c8}),
    ],
    "wep45": [
        ("wep45/pl_grenade.cpp", None, "wep/pl_grenade.cpp"),
        ("wep45/wep45.cpp", "Wep45_init", None, {".rodata": 0x298}),
    ],
    "wep47": [
        ("wep47/pl_rifle.cpp", None, "wep/pl_rifle.cpp"),
        ("wep47/wep47.cpp", "Wep47_init", None, {".rodata": 0x1a8}),
    ],
    "st1_0": [
        ("st1_0/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_0/r100.cpp", "R100Init", "st1/r100.cpp", {".rodata": 0xae8}),
        ("st1_0/r120.cpp", "R120Init", "st1/r120.cpp", {".rodata": 0x10f0}),
        ("st1_0/" + _ST1[0], *_ST1[1:]),
    ],
    "st1_1": [
        ("st1_1/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_1/r101.cpp", "R101Init", "st1/r101.cpp", {".rodata": 0xae8}),
        ("st1_1/r102.cpp", "R102Init", "st1/r102.cpp", {".rodata": 0xeb8}),
        ("st1_1/r103.cpp", "R103Init", "st1/r103.cpp", {".rodata": 0x1098}),
        ("st1_1/r104.cpp", "R104Init", "st1/r104.cpp", {".rodata": 0x11e0}),
        ("st1_1/r105.cpp", "R105Init", "st1/r105.cpp", {".rodata": 0x1488}),
        ("st1_1/r106.cpp", "R106Init", "st1/r106.cpp", {".rodata": 0x17a8}),
        ("st1_1/r107.cpp", "R107Init", "st1/r107.cpp", {".rodata": 0x1a84}),
        ("st1_1/r108.cpp", "R108Init", "st1/r108.cpp", {".rodata": 0x1c40}),
        ("st1_1/r109.cpp", "R109Init", "st1/r109.cpp", {".rodata": 0x1e50}),
        ("st1_1/r10a.cpp", "EmSetNormal", "st1/r10a.cpp", {".rodata": 0x1fe4}),
        ("st1_1/r10b.cpp", "R10bInit", "st1/r10b.cpp", {".rodata": 0x21c4}),
        ("st1_1/" + _ST1[0], *_ST1[1:]),
    ],
    "st1_2": [
        ("st1_2/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_2/r10c.cpp", "R10cInit", "st1/r10c.cpp", {".rodata": 0xae8}),
        ("st1_2/r10d.cpp", "R10dInit", "st1/r10d.cpp", {".rodata": 0xe40}),
        ("st1_2/r10e.cpp", "R10eInit", "st1/r10e.cpp", {".rodata": 0xe80}),
        ("st1_2/r119.cpp", "R119Init", "st1/r119.cpp", {".rodata": 0xec0}),
        ("st1_2/r11a.cpp", "R11aInit", "st1/r11a.cpp", {".rodata": 0x1224}),
        ("st1_2/r11b.cpp", "R11bInit", "st1/r11b.cpp", {".rodata": 0x13c8}),
        ("st1_2/" + _ST1[0], *_ST1[1:]),
    ],
    "st1_3": [
        ("st1_3/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st1_3/r102.cpp", "R102Init", "st1/r102.cpp", {".rodata": 0xae8}),
        ("st1_3/r103.cpp", "R103Init", "st1/r103.cpp", {".rodata": 0xcc8}),
        ("st1_3/r108.cpp", "R108Init", "st1/r108.cpp", {".rodata": 0xe10}),
        ("st1_3/r10f.cpp", "R10fInit", "st1/r10f.cpp", {".rodata": 0x1020}),
        ("st1_3/r111.cpp", "R111Init", "st1/r111.cpp", {".rodata": 0x12ac}),
        ("st1_3/r112.cpp", "R112Init", "st1/r112.cpp", {".rodata": 0x144c}),
        ("st1_3/r113.cpp", "R113Init", "st1/r113.cpp", {".rodata": 0x15ac}),
        ("st1_3/r117.cpp", "R117Init", "st1/r117.cpp", {".rodata": 0x1798}),
        ("st1_3/r118.cpp", "R118Init", "st1/r118.cpp", {".rodata": 0x1b24}),
        ("st1_3/r11c.cpp", "R11cInit", "st1/r11c.cpp", {".rodata": 0x1cc8}),
        ("st1_3/r11d.cpp", "R11dInit", "st1/r11d.cpp", {".rodata": 0x20c8}),
        ("st1_3/r11e.cpp", "R11eInit", "st1/r11e.cpp", {".rodata": 0x22e0}),
        ("st1_3/r11f.cpp", "R11fInit", "st1/r11f.cpp", {".rodata": 0x2540}),
        ("st1_3/" + _ST1[0], *_ST1[1:]),
    ],
    "st2_0": [
        ("st2_0/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_0/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st2_0/r200.cpp", "R200Init", "st2/r200.cpp", {".rodata": 0xb80}),
        ("st2_0/r201.cpp", "R201Init", "st2/r201.cpp", {".rodata": 0xcf8}),
        ("st2_0/r202.cpp", "R202Init", "st2/r202.cpp", {".rodata": 0xf60}),
        ("st2_0/r203.cpp", "R203Init", "st2/r203.cpp", {".rodata": 0x1248}),
        ("st2_0/r207.cpp", "R207Init", "st2/r207.cpp", {".rodata": 0x1508}),
        ("st2_0/r208.cpp", 0xDF38, "st2/r208.cpp", {".rodata": 0x16e0}),
        ("st2_0/r210.cpp", "asl_wait", "st2/r210.cpp", {".rodata": 0x1b28}),
        ("st2_0/r222.cpp", "R222Init", "st2/r222.cpp", {".rodata": 0x1c40}),
        ("st2_0/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_1": [
        ("st2_1/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_1/r204.cpp", "R204Init", "st2/r204.cpp", {".rodata": 0xae8}),
        ("st2_1/r205.cpp", "R205Init", "st2/r205.cpp", {".rodata": 0xe68}),
        ("st2_1/r206.cpp", "R206Init", "st2/r206.cpp", {".rodata": 0x10b8}),
        ("st2_1/r209.cpp", "R209Init", "st2/r209.cpp", {".rodata": 0x1410}),
        ("st2_1/r20a.cpp", "R20aInit", "st2/r20a.cpp", {".rodata": 0x182c}),
        ("st2_1/r20b.cpp", "R20bInit", "st2/r20b.cpp", {".rodata": 0x1918}),
        ("st2_1/r20c.cpp", "R20cInit", "st2/r20c.cpp", {".rodata": 0x1c50}),
        ("st2_1/r20d.cpp", "R20dInit", "st2/r20d.cpp", {".rodata": 0x1e48}),
        ("st2_1/r20e.cpp", "R20eInit", "st2/r20e.cpp", {".rodata": 0x2280}),
        ("st2_1/r20f.cpp", "R20fInit", "st2/r20f.cpp", {".rodata": 0x24f8}),
        ("st2_1/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_2": [
        ("st2_2/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_2/r211.cpp", "R211Init", "st2/r211.cpp", {".rodata": 0xae8}),
        ("st2_2/r212.cpp", "R212Init", "st2/r212.cpp", {".rodata": 0xc80}),
        ("st2_2/r213.cpp", "R213Init", "st2/r213.cpp", {".rodata": 0xfb8}),
        ("st2_2/r214.cpp", "R214Init", "st2/r214.cpp", {".rodata": 0x11d8}),
        ("st2_2/r215.cpp", "R215Init", "st2/r215.cpp", {".rodata": 0x14dc}),
        ("st2_2/r216.cpp", "R216Init", "st2/r216.cpp", {".rodata": 0x177c}),
        ("st2_2/r217.cpp", "R217Init", "st2/r217.cpp", {".rodata": 0x1850}),
        ("st2_2/r218.cpp", "R218Init", "st2/r218.cpp", {".rodata": 0x1a90}),
        ("st2_2/r219.cpp", "R219Init", "st2/r219.cpp", {".rodata": 0x1b48}),
        ("st2_2/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_3": [
        ("st2_3/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st2_3/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st2_3/r21a.cpp", "R21aInit", "st2/r21a.cpp", {".rodata": 0xb80}),
        ("st2_3/r21b.cpp", "R21bInit", "st2/r21b.cpp", {".rodata": 0xde8, ".data": 0xA8}),
        ("st2_3/r21d.cpp", "R21dInit", "st2/r21d.cpp", {".rodata": 0xf08}),
        ("st2_3/r220.cpp", "R220Init", "st2/r220.cpp", {".rodata": 0x11ac}),
        ("st2_3/r221.cpp", "R221Init", "st2/r221.cpp", {".rodata": 0x1268}),
        ("st2_3/r223.cpp", "R223Init", "st2/r223.cpp", {".rodata": 0x1520}),
        ("st2_3/r224.cpp", "R224Init", "st2/r224.cpp", {".rodata": 0x1788}),
        ("st2_3/r225.cpp", "R225Init", "st2/r225.cpp", {".rodata": 0x1a80}),
        ("st2_3/r226.cpp", "R226Init", "st2/r226.cpp", {".rodata": 0x1cd0}),
        ("st2_3/r227.cpp", "R227Init", "st2/r227.cpp", {".rodata": 0x2140}),
        ("st2_3/r228.cpp", "R228Init", "st2/r228.cpp", {".rodata": 0x2430}),
        ("st2_3/r229.cpp", "R229Init", "st2/r229.cpp", {".rodata": 0x26bc}),
        ("st2_3/r22a.cpp", "R22aInit", "st2/r22a.cpp", {".rodata": 0x28f8}),
        ("st2_3/r22b.cpp", "R22bInit", "st2/r22b.cpp", {".rodata": 0x2a78}),
        ("st2_3/" + _ST2[0], *_ST2[1:]),
    ],
    "st2_4": [
        ("st2_4/em_wrap.cpp", None, "st/em_wrap_v2.cpp", {".rodata": 0x0}),
        ("st2_4/r22c.cpp", "R22cInit", "st2/r22c.cpp", {".rodata": 0xac4}),
        ("st2_4/" + _ST2[0], *_ST2[1:]),
    ],
    "st4_0": [
        ("st4_0/em_wrap.cpp", None, "st/em_wrap_v2.cpp", {".rodata": 0x0}),
        ("st4_0/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xac4}),
        ("st4_0/r400.cpp", "R400Init", "st4/r400.cpp", {".rodata": 0xb60}),
        ("st4_0/r402.cpp", "R402Init", "st4/r402.cpp", {".rodata": 0xdf0}),
        ("st4_0/r403.cpp", "R403Init", "st4/r403.cpp", {".rodata": 0x1000}),
        ("st4_0/r404.cpp", "R404Init", "st4/r404.cpp", {".rodata": 0x1338}),
        ("st4_0/r405.cpp", "snd_tbl_set", "st4/r405.cpp", {".rodata": 0x1478}),
        ("st4_0/r406.cpp", "R406Init", "st4/r406.cpp", {".rodata": 0x16dc}),
        ("st4_0/r40a.cpp", "r40a_DuraluminCaseOpen", "st4/r40a.cpp", {".rodata": 0x17f0}),
        ("st4_0/r40b.cpp", "R40bInit", "st4/r40b.cpp", {".rodata": 0x1888}),
        ("st4_0/r40c.cpp", "R40cInit", "st4/r40c.cpp", {".rodata": 0x19e8}),
        ("st4_0/r40d.cpp", "R40dInit", "st4/r40d.cpp", {".rodata": 0x1b8c}),
        ("st4_0/r40e.cpp", "R40eInit", "st4/r40e.cpp", {".rodata": 0x1cf8}),
        ("st4_0/r40f.cpp", "R40fInit", "st4/r40f.cpp", {".rodata": 0x2008}),
        ("st4_0/r410.cpp", "R410Init", "st4/r410.cpp", {".rodata": 0x20b4}),
        ("st4_0/r411.cpp", "R411Init", "st4/r411.cpp", {".rodata": 0x2130}),
        # st4.cpp includes map_obj.h/light.h/widget.h/atari.h (their strings + its cManager<cLight> block)
        ("st4_0/" + _ST4[0], *_ST4[1:], {".rodata": 0x21AC}),
    ],
    # st3_0 (disc 2): em_wrap.cpp (third revision, src/st/em_wrap_v3.cpp: cEmRouteRun/cEmRouteExec), cSceObj.cpp (stripped: no
    # *Move3_y/setStart members), then 13 rooms. r300.cpp starts at setResetNum (the reset
    # counter helpers precede R300Init, like st2_0's r208) and owns the module's named cManager<cLight> pair;
    # r304's group starts with event.h, r30c's with map_obj.h, r30e has no cFlag.set()/atari.h string
    # ([HALT][flag_rsf.h][r30e.cpp]). st3.cpp (src/st3/st3.cpp): map_obj.h/light.h/widget.h/sofdec.h/event.h
    # strings, "movie/r333_ev.sfd" (a never-called inline), a nameless cLight block after _unresolved.
    "st3_0": [
        ("st3_0/em_wrap.cpp", None, "st/em_wrap_v3.cpp", {".rodata": 0x0}),
        ("st3_0/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st3_0/r300.cpp", "setResetNum", "st3/r300.cpp", {".rodata": 0xb80}),
        ("st3_0/r301.cpp", "R301Init", "st3/r301.cpp", {".rodata": 0x1060}),
        ("st3_0/r303.cpp", "R303Init", "st3/r303.cpp", {".rodata": 0x12cc}),
        ("st3_0/r304.cpp", "R304Init", "st3/r304.cpp", {".rodata": 0x1470}),
        ("st3_0/r305.cpp", "R305Init", "st3/r305.cpp", {".rodata": 0x175c}),
        ("st3_0/r306.cpp", "R306Init", "st3/r306.cpp", {".rodata": 0x1810}),
        ("st3_0/r307.cpp", "R307Init", "st3/r307.cpp", {".rodata": 0x19b0}),
        ("st3_0/r308.cpp", "R308Init", "st3/r308.cpp", {".rodata": 0x1bdc}),
        ("st3_0/r309.cpp", "R309Init", "st3/r309.cpp", {".rodata": 0x1dac}),
        ("st3_0/r30a.cpp", "R30aInit", "st3/r30a.cpp", {".rodata": 0x1e48}),
        ("st3_0/r30b.cpp", "R30bInit", "st3/r30b.cpp", {".rodata": 0x2080}),
        ("st3_0/r30c.cpp", "R30cInit", "st3/r30c.cpp", {".rodata": 0x2390}),
        ("st3_0/r30e.cpp", "R30eInit", "st3/r30e.cpp", {".rodata": 0x2598}),
        ("st3_0/st3.cpp", "set", "st3/st3.cpp", {".rodata": 0x25e4}),
    ],
    # st3_1 (disc 2): em_wrap.cpp (first revision, "cEmControl::SetPatrol"), cSceObj.cpp, r30d, r30f (includes
    # map_obj.h/light.h/widget.h: the module's named cManager<cLight> pair after gate_open), r310, r311 (event.h
    # first; nameless cLight block fn_st3_1_E73C), r312, then st3.cpp (map_obj.h/light.h/widget.h/sofdec.h/event.h
    # strings + "movie/r333_ev.sfd" + its cLight block after _unresolved).
    "st3_1": [
        ("st3_1/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st3_1/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st3_1/r30d.cpp", "R30dInit", "st3/r30d.cpp", {".rodata": 0xb80}),
        ("st3_1/r30f.cpp", "R30fInit", "st3/r30f.cpp", {".rodata": 0xcb0}),
        ("st3_1/r310.cpp", "R310Init", "st3/r310.cpp", {".rodata": 0xfa8}),
        ("st3_1/r311.cpp", "R311Init", "st3/r311.cpp", {".rodata": 0x1158}),
        ("st3_1/r312.cpp", "R312Init", "st3/r312.cpp", {".rodata": 0x13d0}),
        ("st3_1/st3.cpp", "set", "st3/st3.cpp", {".rodata": 0x144c}),
    ],
    # Disc 2 island stage module st3_2 (r315..r31d). em_wrap.cpp is the first revision (has the
    # "cEmControl::SetPatrol" string); cSceObj.cpp keeps move1/move2/move3/getVibrationValue/setStartPos.
    # r316/r317/r31a/r31b/r31c include light.h (cManager<cLight> block after each); r31b's block is
    # followed by the named CountDown::checkState linkonce copy (r31c's copy is nameless in its block).
    # st3.cpp includes map_obj.h/light.h/widget.h/sofdec.h/event.h (header strings + a cLight block).
    "st3_2": [
        ("st3_2/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st3_2/cSceObj.cpp", "cSceObj::move1", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st3_2/r315.cpp", "R315Init", "st3/r315.cpp", {".rodata": 0xb80}),
        ("st3_2/r316.cpp", "R316Init", "st3/r316.cpp", {".rodata": 0xc2c}),
        ("st3_2/r317.cpp", "R317Init", "st3/r317.cpp", {".rodata": 0xe28}),
        ("st3_2/r318.cpp", "R318Init", "st3/r318.cpp", {".rodata": 0x12f8}),
        ("st3_2/r31a.cpp", "R31aInit", "st3/r31a.cpp", {".rodata": 0x1488}),
        ("st3_2/r31b.cpp", "R31bInit", "st3/r31b.cpp", {".rodata": 0x15e8}),
        ("st3_2/r31c.cpp", "R31cInit", "st3/r31c.cpp", {".rodata": 0x1b28}),
        ("st3_2/r31d.cpp", "R31dInit", "st3/r31d.cpp", {".rodata": 0x1f18}),
        ("st3_2/st3.cpp", "set", "st3/st3.cpp", {".rodata": 0x1f58}),
    ],
    # Disc 2 island stage module st3_3 (r320, r321, r325..r333). em_wrap.cpp is the first revision
    # ("cEmControl::SetPatrol"); cSceObj.cpp keeps move/move1/move2/move3/initMove1_all/setMove1_all/
    # getVibrationValue/setSrcDstPos/setStartPos. r320 includes map_obj.h/light.h/widget.h and owns the
    # module's named cManager<cLight> pair; r321/r327/r331/r332/r333 have nameless cLight blocks
    # (r321/r327/r331/r333 start with map_obj.h/light.h/widget.h before the cFlag.set() string); r328 has
    # no cFlag.set()/atari.h string, its group is [HALT][flag_rsf.h][r328.cpp]. st3.cpp includes
    # map_obj.h/light.h/widget.h/sofdec.h/event.h (header strings + its cLight block after the CountDown code).
    "st3_3": [
        ("st3_3/em_wrap.cpp", None, "st/em_wrap.cpp", {".rodata": 0x0}),
        ("st3_3/cSceObj.cpp", "cSceObj::move", "st/cSceObj.cpp", {".rodata": 0xae8}),
        ("st3_3/r320.cpp", "emset", "st3/r320.cpp", {".rodata": 0xb80}),
        ("st3_3/r321.cpp", "R321Init", "st3/r321.cpp", {".rodata": 0x10a8}),
        ("st3_3/r325.cpp", "R325Init", "st3/r325.cpp", {".rodata": 0x12f0}),
        ("st3_3/r326.cpp", "R326Init", "st3/r326.cpp", {".rodata": 0x140c}),
        ("st3_3/r327.cpp", "R327Init", "st3/r327.cpp", {".rodata": 0x14c8}),
        ("st3_3/r328.cpp", "R328Init", "st3/r328.cpp", {".rodata": 0x16f8}),
        ("st3_3/r329.cpp", "R329Init", "st3/r329.cpp", {".rodata": 0x1738}),
        ("st3_3/r330.cpp", "R330Init", "st3/r330.cpp", {".rodata": 0x18a0}),
        ("st3_3/r331.cpp", "R331Init", "st3/r331.cpp", {".rodata": 0x1a78}),
        ("st3_3/r332.cpp", "R332Init", "st3/r332.cpp", {".rodata": 0x1ca8}),
        ("st3_3/r333.cpp", "R333Init", "st3/r333.cpp", {".rodata": 0x21f8}),
        ("st3_3/st3.cpp", "set", "st3/st3.cpp", {".rodata": 0x24b0}),
    ],
    # Debug tool modules: <tool>.cpp, then the tool library objects t_prim.cpp / t_util.cpp (the full
    # versions of the DOL's game/t_prim, game/t_util, which the DOL link dead-stripped), then the shared
    # tools.cpp (D:/Bio4/Prog/tools.cpp: _prolog runs the ctors and ToolsTask, which dispatches
    # DebugMenuSelected to the Tool* entry of every tool module). Each object that includes light.h
    # carries its own cManager<cLight> instantiations behind its code (see LINKONCE below).
    # tools.cpp is also the last object of t_camera/t_light/t_sce/t_event (same bytes); t_esp/Tools/t_id
    # have their linkonce orphan sections behind it and t_movie has other objects after it.
    # t_camera/t_light/t_event share db_light.cpp (D:/Bio4/Prog/db_light.cpp: cLightTool, cDbLit,
    # cLitPathTool + the cManager<cLight>/cVarRange<u8> instantiations, 0x12408 bytes, byte-identical;
    # t_sce carries an older build of it, tools/db_light_v2.cpp). db_sctrl.cpp (Sctrl*/DbSctrl/grab*/
    # draw*/pos*, 0x2D4C bytes) is the same object in t_id and t_event. The object with cFileList and
    # the `global constructors keyed to cFileList_init` (db_toolbase.h inlines; t_event's copy also has
    # the cDbgWindow/cDbgButton bodies) is db_filelist.cpp (name unknown). Each module's t_util.cpp is
    # a different build of src/tools/t_util.cpp (t_light/t_esp: Init/QuitDefault only, no .data,
    # t_util_nomenu.cpp; t_event/t_sce/t_movie: + ToolMenuDisp/_cur with a local old_menu and no zero
    # word, t_util_menu.cpp; t_id: no function, .data without the zero word, t_util_id.cpp; t_camera: no
    # out-of-line function at all, only the header strings, .data and the cManager<cLight> linkonce
    # block; Tools: the full file). t_camera's t_prim.cpp has 5 functions and includes t_util.h's headers.
    "t_camera": [
        ("t_camera/db_light.cpp", None, "tools/db_light.cpp"),
        ("t_camera/t_camera.cpp", "ToolCamera", None, {".rodata": 0x1640}),
        # tcGetFileName..tcSetBesideCamera (export/import, game camera bridge) and tcCameraMove..
        # tcDrawParametricCurve (drawing helpers): two more objects whose file names are not in the binary
        ("t_camera/t_camera_data.cpp", "tcGetFileName", None, {".rodata": 0x2090}),
        ("t_camera/t_camera_draw.cpp", "tcCameraMove", None, {".rodata": 0x2298}),
        ("t_camera/t_prim.cpp", "TprimInitEnv2D3D", "tools/t_prim.cpp", {".rodata": 0x23A0}),
        # every t_util function was dead-stripped here: header strings, old_menu/old_num/cursor_s/
        # flicker (.data), globalCamera + the flag backups (.bss) and the cManager<cLight> block remain
        ("t_camera/t_util.cpp", 0x1C954, "tools/t_util.cpp", {".rodata": 0x2400, ".data": 0x76C, ".bss": 0x162C0}),
        ("t_camera/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
    "t_light": [
        ("t_light/db_light.cpp", None, "tools/db_light.cpp"),
        ("t_light/t_light.cpp", "ToolLight", None, {".rodata": 0x1640}),
        ("t_light/t_scroll.cpp", "ToolScroll", None, {".rodata": 0x174C}),
        ("t_light/t_util.cpp", "TutilInitDefault", "tools/t_util_nomenu.cpp", {".rodata": 0x1EE0}),
        ("t_light/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
    "t_event": [
        ("t_event/db_light.cpp", None, "tools/db_light.cpp"),
        # db_sctrl.o starts with the pool of a dead-stripped function (DF magic + 1.0f, unreferenced)
        ("t_event/db_sctrl.cpp", "SctrlInitAxisRange", "tools/db_sctrl.cpp", {".rodata": 0x1640}),
        # Tools' db_toolbase.cpp object (its linkonce base-class inlines end it), then the cFileList object;
        # the file list instance (unreferenced from its own code) is the first 0x18 of .bss after db_light
        ("t_event/db_toolbase.cpp", "MakeCol", "tools_mod/db_toolbase.cpp"),
        ("t_event/db_filelist.cpp", "cFileList::init", "tools/db_filelist.cpp", {".rodata": 0x1A20, ".bss": 0xAC}),
        ("t_event/t_event.cpp", "ToolEvent", None, {".rodata": 0x1A80, ".bss": 0xC4}),
        ("t_event/t_util.cpp", "TutilInitDefault", "tools/t_util_menu.cpp", {".rodata": 0x2508}),
        ("t_event/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
    "t_sce": [
        ("t_sce/db_light.cpp", None, "tools/db_light_v2.cpp"),
        ("t_sce/db_filelist.cpp", "cFileList::init", "tools/db_filelist.cpp", {".bss": 0xAC}),
        ("t_sce/t_block.cpp", "ToolBlock", None, {".rodata": 0x16A0}),
        # the same object as Tools' t_sce_at.cpp (D:/Bio4/Prog/t_sce_at.cpp)
        ("t_sce/t_sce_at.cpp", "ToolSceAt", "tools/t_sce_at.cpp", {".rodata": 0x1AD0}),
        ("t_sce/t_sce_item.cpp", "ToolSceItem", None, {".rodata": 0x28D0}),
        ("t_sce/t_util.cpp", "TutilInitDefault", "tools/t_util_menu.cpp", {".rodata": 0x3248}),
        ("t_sce/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
    # t_id: db_path.cpp, db_sctrl.cpp, t_id.cpp (toolId*/idEdit*/DbRandom + its templates and the
    # constructors keyed to ToolInterfaceDesign), the function-less t_util.cpp (its header strings at
    # .rodata 0xE48, .text = the nameless cManager<cLight> block), then tools.cpp built with TOOLS_ARRAY
    # (CFLAGS below): _prolog..._unresolved, ToolArrayPush/ToolWorkPop, and only then its cManager<cLight>
    # block and the cManager<T>::arrayPush/arrayPop instantiations of six managers (t_esp's and Tools'
    # tools.cpp end the same way, t_esp's with ToolEmArraySet too).
    "t_id": [
        ("t_id/db_path.cpp", None),
        ("t_id/db_sctrl.cpp", "SctrlInitAxisRange", "tools/db_sctrl.cpp", {".rodata": 0xF0}),
        ("t_id/t_id.cpp", "toolIdInit", None, {".rodata": 0x328, ".bss": 0xC}),
        ("t_id/t_util.cpp", 0xDBA0, "tools/t_util_id.cpp", {".rodata": 0xE48, ".data": 0x298, ".bss": 0x14DE34}),
        ("t_id/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
    "t_emlist": [
        ("t_emlist/t_emlist.cpp", None),
        ("t_emlist/t_prim.cpp", "TprimInitEnv2D3D", "tools/t_prim.cpp"),
        # t_util's header strings (map_obj.h/light.h/widget.h) and its .data (old_menu, the menu
        # statics) are not addressed by its code
        ("t_emlist/t_util.cpp", "TutilInitDefault", "tools/t_util.cpp", {".rodata": 0x14E0, ".data": 0x29FC}),
        ("t_emlist/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
    # t_movie: t_sce's build of db_light.cpp, the sound test (Snd_test_*/test_*/disp_*/aram_*: no file
    # string, snd_test.cpp by its prefix), t_movie.cpp (this module's entry object: _prolog/_epilog/
    # _unresolved, MovieTest/movie_test_*, SoundTest and the constructors keyed to _prolog), a 10-function
    # build of t_prim.cpp, the SE attack editor (ToolSeAt/seAt*/preview_*), the sound volume editor
    # (getInfoData..ToolSndVolEdit) and t_event's build of t_util.cpp.
    "t_movie": [
        ("t_movie/db_light.cpp", None, "tools/db_light_v2.cpp"),
        ("t_movie/snd_test.cpp", "Snd_test_mode"),
        ("t_movie/t_movie.cpp", "_prolog", None, {".rodata": 0x2644}),
        ("t_movie/t_prim.cpp", "TprimInitEnv2D3D"),
        ("t_movie/t_se_at.cpp", "ToolSeAt", None, {".rodata": 0x2728}),
        ("t_movie/t_snd_vol.cpp", "getInfoData"),
        ("t_movie/t_util.cpp", "TutilInitDefault", "tools/t_util_menu.cpp", {".rodata": 0x3510}),
    ],
    # Sscrn (sub screen): ss_cap/ss_debug/ss_file/ss_item/ss_main/ss_map/ss_pzzl/ss_shop/ss_term.cpp by
    # their __FILE__ strings, alphabetical like every other module; the weapon/character model tables
    # (weaponFilename..wep19Init) between ss_map and ss_pzzl have no file string (ss_model.cpp). The
    # ss_Draw_* helpers after ss_item are a separate object (they follow ss_item's end-of-file blocks:
    # synthesized destructors and Widget::quit/init/move; real name unknown, sorted between ss_item and
    # ss_main: ss_item_draw.cpp, .rodata = its three 0.0f pools); ss_main
    # starts at _prolog (its constructors are keyed to _prolog); ss_term carries MakeCol/cDbgWindow/
    # cFileList (constructors keyed to MakeCol). Every unit's .rodata start is pinned at its header-string
    # group (map_obj.h/light.h/widget.h...).
    "Sscrn": [
        ("Sscrn/ss_cap.cpp", None),
        ("Sscrn/ss_debug.cpp", "SscrnDebugMenu", None, {".rodata": 0x240}),
        ("Sscrn/ss_file.cpp", "getMsgNum", None, {".rodata": 0x688}),
        ("Sscrn/ss_item.cpp", "itemNameDisp", None, {".rodata": 0x928, ".data": 0x550}),
        ("Sscrn/ss_item_draw.cpp", "ss_Draw_tpl", None, {".rodata": 0xCC0}),
        ("Sscrn/ss_main.cpp", "_prolog", None, {".rodata": 0xCD0}),
        ("Sscrn/ss_map.cpp", "getStageNo", None, {".rodata": 0x1248, ".data": 0x590}),
        ("Sscrn/ss_model.cpp", "weaponFilename", None, {".rodata": 0x22E0}),
        ("Sscrn/ss_pzzl.cpp", "pzzlClearZ", None, {".rodata": 0x26D8}),
        ("Sscrn/ss_shop.cpp", "shopClearZ", None, {".rodata": 0x2BC0}),
        ("Sscrn/ss_term.cpp", "MakeCol", None, {".rodata": 0x3128}),
    ],
    # Tools: the general debug-tool module, one object per tool in file-name order: db_light.cpp (a
    # newer build than t_camera's: cLightTool ctor/move, lightAnalysis), db_mod.cpp (model viewer,
    # constructors keyed to dbModSetViewFlag), db_toolbase.cpp (MakeCol/DbgDrawBox/cDbgWindow, the
    # db_toolbase.h bodies), t_atari (ToolAtari .. constructors keyed to ToolAtari), t_cons, t_dr (tDr*),
    # t_eminfo, t_esp_area (IsWorkAlive..OptionExec + ToolEspArea + cDbgEditWindow<ESP_AREA>), t_flr_at,
    # t_lightarea (namespace t_lightarea, starts with its own __builtin_new/delete), t_mes, t_motseq,
    # t_mv (ToolMotionViewer), the full t_prim.cpp (18 functions), t_rck.cpp, t_sce_at.cpp (the same
    # object as t_sce's), t_tplview, the full t_util.cpp (TutilGet3DPosXZ* etc.), t_vib, tools.cpp.
    # Unit names below keep the vendor-facing "Tools/..." spelling (they are labels: splits.txt,
    # sym_map.tsv, symbols.txt and docs all key off them and none were regenerated for this rename).
    # The physical source for the module's own files (the ones that need an explicit override below)
    # moved from src/Tools/ to src/tools_mod/: on a case-insensitive filesystem (APFS) src/Tools/ and
    # src/tools/ are the same directory, and three of this module's own filenames (t_prim.cpp,
    # t_util.cpp, tools.cpp) also exist under src/tools/ with different (shared-body) content, so
    # src/Tools/ could not be told apart from src/tools/ by path alone on such a host. src/tools/
    # (the shared bodies compiled into t_camera/t_emlist/t_esp/t_event/t_id/t_light/t_movie/t_sce, and
    # already referenced here by explicit override) is untouched.
    "Tools": [
        ("Tools/db_light.cpp", None, "tools/db_light_tools.cpp"),
        ("Tools/db_mod.cpp", "dbModSetViewFlag", "tools/db_mod.cpp", {".rodata": 0x1640}),
        ("Tools/db_toolbase.cpp", "MakeCol", "tools_mod/db_toolbase.cpp"),
        # t_atari.cpp's header-string group starts with atari.h's cFlag.set() message (0x2578), like the rooms'
        ("Tools/t_atari.cpp", "ToolAtari", "tools_mod/t_atari.cpp", {".rodata": 0x2578}),
        ("Tools/t_cons.cpp", "ToolCons", "tools_mod/t_cons.cpp", {".rodata": 0x29C8}),
        ("Tools/t_dr.cpp", "tDrExit", "tools_mod/t_dr.cpp", {".rodata": 0x2D6C}),
        # t_eminfo.cpp's group starts with atari.h's cFlag.set() message (0x3088, 8-aligned: the 4-byte pad
        # before it is the linker's, t_dr's .rodata ends at 0x3084)
        ("Tools/t_eminfo.cpp", "ToolEmInfo", "tools_mod/t_eminfo.cpp", {".rodata": 0x3088}),
        ("Tools/t_esp_area.cpp", "IsWorkAlive", "tools_mod/t_esp_area.cpp", {".rodata": 0x3468}),
        ("Tools/t_flr_at.cpp", "flrAtInit", "tools_mod/t_flr_at.cpp", {".rodata": 0x3A88}),
        ("Tools/t_lightarea.cpp", "__builtin_new", "tools_mod/t_lightarea.cpp", {".rodata": 0x3FF8}),
        ("Tools/t_mes.cpp", "ToolMes", "tools_mod/t_mes.cpp", {".rodata": 0x4680, ".data": 0x2170}),
        ("Tools/t_motseq.cpp", "ToolMotSeq", "tools_mod/t_motseq.cpp", {".rodata": 0x4860}),
        ("Tools/t_mv.cpp", "ToolMotionViewer", "tools_mod/t_mv.cpp", {".rodata": 0x4E10, ".bss": 0x13DAD0}),
        ("Tools/t_prim.cpp", "TprimInitEnv2D3D", "tools_mod/t_prim.cpp"),
        # t_rck.cpp's header-string group starts with atari.h's cFlag.set() message (0x5000)
        ("Tools/t_rck.cpp", "ToolRctRouteCheck", "tools_mod/t_rck.cpp", {".rodata": 0x5000}),
        ("Tools/t_sce_at.cpp", "ToolSceAt", "tools/t_sce_at.cpp", {".rodata": 0x53B8}),
        ("Tools/t_tplview.cpp", "ToolTplView", "tools_mod/t_tplview.cpp", {".rodata": 0x61B8}),
        ("Tools/t_util.cpp", "TutilInitDefault", "tools_mod/t_util.cpp", {".rodata": 0x6370}),
        ("Tools/t_vib.cpp", "ToolVibEdit", "tools_mod/t_vib.cpp"),
        ("Tools/tools.cpp", "_prolog", "tools_mod/tools.cpp"),
    ],
    # t_esp: yet another db_light.cpp build, a db_mod.cpp build with the model-set loader
    # (dbModBinName..dbModelSetCamera), db_port.cpp (GetActiveModel/MakeCol/DB_* helpers, the EspTool*
    # bridge), the DB_RECT..DB_SLIDEBAR and DB_WINDOW..DB_PRIM_ARRAY widget classes (two objects with
    # their own header-string groups, names unknown: db_widget.cpp / db_window.cpp), t_esp.cpp (namespace
    # t_esp, starts with __builtin_new/delete like t_lightarea), t_light's build of t_util.cpp, tools.cpp
    # with the module's linkonce tail.
    "t_esp": [
        ("t_esp/db_light.cpp", None, "tools/db_light_esp.cpp"),
        ("t_esp/db_mod.cpp", "dbModSetViewFlag", "tools/db_mod.cpp", {".rodata": 0x1640}),
        # every header-string group of this module starts with atari.h's cFlag.set() message
        ("t_esp/db_port.cpp", "GetActiveModel", None, {".rodata": 0x23D0}),
        # db_widget.o ends with its linkonce tail: the cManager<cLight> block, then the seven implicit
        # destructors its vtables mark used (DB_WINDOW..DB_SLIDEBAR); db_window.o starts at DB_MOUSE
        ("t_esp/db_widget.cpp", "DB_RECT::ChkHitRect", None, {".rodata": 0x2CA8}),
        ("t_esp/db_window.cpp", "DB_MOUSE::DB_MOUSE", None, {".rodata": 0x3410}),
        ("t_esp/t_esp.cpp", "__builtin_new", None, {".rodata": 0x35E0}),
        ("t_esp/t_util.cpp", "TutilInitDefault", "tools/t_util_nomenu.cpp", {".rodata": 0x53B0}),
        ("t_esp/tools.cpp", "_prolog", "tools/tools.cpp"),
    ],
}

# Units whose compiled object does not yet match: linked from the original bytes instead.
# Disc 2 island stage modules (added 2026-09-18): linked from the split original objects until matched.
NON_MATCHING = set()
# The 16 Ganado modules (em10..em20) are three objects. (1) The same em10.cpp ("D:/Bio4/Prog/em10.cpp":
# cEm10 and its em10*/em1c*/plem10* helpers, .text 0-0x43518, .rodata 0-0x1D40, all of .data/.bss,
# byte-identical in every module). (2) A header-only object whose name is not in the binary
# (src/em10/em10_tmpl.cpp, shared too): the 0x3B8-byte nameless cManager<cLight> linkonce block
# (.text 0x43518-0x438D0, the `bl`s resolve to em10.cpp's named countActiveWork/create(int)) and a
# second copy of the [cFlag.set()][atari.h][light.h][dmg.h][ctrl.h] header strings + the five
# cManager<cLight> strings (.rodata 0x1D40-0x1E88) - GCC 2.95 merges identical strings within one
# translation unit, so the duplicated header strings prove a second object, and its block sits
# before _prolog, so it is not the entry object. (3) ONE small per-enemy object, name not in the
# binary either (src/<em>/<em>_set.cpp): the SN entry points (_prolog: OSReport("em10 prolog Ok\n")
# in every module, EmInitFunc = EmXXInit, Em10SetFunc = EmXXSet; _epilog, _unresolved) followed by
# EmXXInit/Set/WeaponSet; its .rodata is [cFlag.set()][atari.h] (every module includes atari.h)
# [light.h (em1d/em1e/em1f/em20 only)] ["em10 prolog Ok"] [cManager<cLight> strings (those four,
# with a second 0x3B8 block after EmXXWeaponSet)]. The .rodata starts of (2) and (3) are pinned (4th
# element) because their header strings are unreferenced. (The zero ADDR16 fields of _prolog's
# EmXXInit/EmXXSet references say nothing about the object boundary: the original linker never added
# the input-section displacement, see docs/matching.md "REL modules".)
for _em in ["em10", "em11", "em12", "em13", "em14", "em15", "em16", "em17", "em19", "em1a", "em1b",
            "em1c", "em1d", "em1e", "em1f", "em20"]:
    UNITS[_em] = [
        (f"{_em}/em10.cpp", None, "em10/em10.cpp"),
        (f"{_em}/em10_tmpl.cpp", 0x43518, "em10/em10_tmpl.cpp", {".rodata": 0x1D40}),
        (f"{_em}/{_em}_set.cpp", "_prolog", None, {".rodata": 0x1E88}),
    ]

# Module units the original REL link dead-stripped at function level (bodies gone, strings and constant
# pools kept, like the DOL's SDK/dead game functions): tools/strip_unused.py --module removes every
# function the module's sym_map.tsv does not list for the unit (configure.py adds the post-build step).
# Extra compiler flags per module. Sscrn was built with -fno-implement-inlines: its widget classes carry
# in-class constructors (`SsFileMain() : Widget<SUB_SCREEN>(5) {}` — the per-class link counts SubScreenTask
# inlines) that no unit emits out of line, while every DOL unit emits such members (cp/decl2.c
# import_export_decl: a vtable-owning class's non-virtual inline members are external under the flag).
# Tools/t_event: cDbgButton's in-class constructor (db_toolbase.h) is inlined into cDbgWindow::AddButton
# and has no out-of-line body in the module either (same flag, same evidence as Sscrn's widgets).
# t_id/t_esp/Tools: tools.cpp defines ToolArrayPush/ToolWorkPop (t_esp: ToolEmArraySet) after _unresolved
# (TOOLS_ARRAY; Tools' object with it is byte-identical to the split, the module linkonce rule places the
# six cManager<T>::arrayPush/arrayPop instantiations behind the cLight block).
CFLAGS = {
    "Sscrn": ["-fno-implement-inlines"],
    "t_id": ["-DTOOLS_ARRAY"],
    "t_esp": ["-DTOOLS_ARRAY", "-DTOOLS_EM_ARRAY"],
    "Tools": ["-fno-implement-inlines", "-DTOOLS_ARRAY"],
    "t_event": ["-fno-implement-inlines"],
}

# Per-unit flag additions (appended after the module's CFLAGS, a later -f flag wins). db_toolbase.cpp
# (Tools; the same object in t_event/Sscrn) was compiled with the default -fimplement-inlines: its
# in-class non-virtual cDbgWindow::Init is in the object, emitted between the deferred ~cDbgButton and
# ~cDbgWindow (the two in-class destructors), and the two base vtables come out WindowBase then
# ButtonBase, which needs both destructors deferred (see the db_toolbase.h notes).
UNIT_CFLAGS = {
    "Tools/db_toolbase.cpp": ["-fimplement-inlines"],
    "t_event/db_toolbase.cpp": ["-fimplement-inlines"],
}

STRIP_UNUSED = {
    f"{_m}/em_wrap.cpp" for _m in ["st1_0", "st1_1", "st1_2", "st1_3", "st2_0", "st2_1", "st2_2", "st2_3", "st2_4", "st4_0", "st3_0", "st3_1", "st3_2", "st3_3"]
} | {f"{_m}/cSceObj.cpp" for _m in ["st2_0", "st2_3", "st4_0", "st3_0", "st3_1", "st3_2", "st3_3"]} | {
    # st3.cpp's count-down helpers (st3_setCountDownTimer .. st3_endCountDown, CountDown::checkState) survive only
    # in st3_3 (r331 calls them); the other island modules' links dropped them (strings kept: "movie/r333_ev.sfd").
    f"{_m}/st3.cpp" for _m in ["st3_0", "st3_1", "st3_2"]
} | {
    # rooms whose original object lost a never-called static function (strings and pool kept)
    "st2_3/r229.cpp",
    "st2_3/r226.cpp",
    "st2_2/r216.cpp",
    "st2_1/r20d.cpp",
    # em2f: a never-called static (six pool constants between em2fRouteCk and em2fWaterEffSet)
    "em2f/em2f.cpp",
    # em31: the never-called single-link Em31ClothSet (five pool constants between em31RouteCk and Em31ClothSet2)
    "em31/em31.cpp",

    # the tool library objects are the t_emlist versions minus what the module never calls
    "t_camera/t_prim.cpp", "t_camera/t_util.cpp", "t_light/t_util.cpp", "t_event/t_util.cpp", "t_sce/t_util.cpp",
    "t_movie/t_util.cpp", "t_esp/t_util.cpp", "t_id/t_util.cpp",
    # t_movie's t_prim.cpp is the full (Tools) build minus the functions the module never calls
    "t_movie/t_prim.cpp",
    # t_sce / t_movie's db_light.cpp is Tools' build minus the cLightTool / cLitPathTool ctors, dtors,
    # move, lightAnalysis, expand, getCutNo and the cVarRange<u8> members only they used
    "t_sce/db_light.cpp", "t_movie/db_light.cpp",
    # db_sctrl.cpp starts with the pool of a dead-stripped function
    "t_id/db_sctrl.cpp", "t_event/db_sctrl.cpp",
    # db_widget.cpp: the never-called DB_SLIDEBAR constructor (pool kept) and the dead delete-all
    # helper that makes our cc1plus synthesize the implicit destructors
    "t_esp/db_widget.cpp",
    # db_port.cpp: two never-called helpers (DB_DrawPoint, DB_VecClear) whose pools stayed
    "t_esp/db_port.cpp",
    # db_window.cpp: the dead helper that carries the DB_NUMERIC range table
    "t_esp/db_window.cpp",
    # ss_term.cpp: the never-called cDbgWindow::AddButton (its string stays after MakeCol's pool; it
    # references _vt.10cDbgButton so the vtable and ~cDbgButton come out in finish_file round 1), the
    # dead screenPos2terminalPos whose pool (0.5, pi, 180, 240) follows terminalCameraInit's, and the
    # dead ssTermWidgetKill that names Widget<SUB_SCREEN>::~Widget (see the source)
    "Sscrn/ss_term.cpp",
    # db_mod.cpp: one object (src/tools/db_mod.cpp) in both modules; Tools lost the t_esp loader entry
    # points / DB_MODEL_FILES::append / dbModMotionSet, t_esp the view-flag getters / dbModMotionSetSeq /
    # dbModGetMotFilename (strings and pools of both stay, .rodata/.data are identical)
    "Tools/db_mod.cpp", "t_esp/db_mod.cpp",
} | {
    # the grenade player routines: two never-called routines between set10 and set20 whose pools and
    # static Vec stayed (src/wep/pl_grenade.cpp wep19_r3_set50/set60)
    f"{_m}/pl_grenade.cpp" for _m in ["wep19", "wep30", "wep41", "wep42", "wep45"]
} | {
    # the Ganado library: two never-called helpers whose pools stayed (em10FindFloorCk,
    # plem10NeckBreakCamMove in src/em10/em10.cpp)
    f"{_m}/em10.cpp" for _m in ["em10", "em11", "em12", "em13", "em14", "em15", "em16", "em17", "em19", "em1a", "em1b",
                                 "em1c", "em1d", "em1e", "em1f", "em20"]
}

# Linkonce (template) functions the original REL link dropped although no unit of the module names
# the class instance (tools/ngccc.py place_linkonce_module keeps such copies nameless by default):
# wep14.cpp / wep17.cpp include light.h (header string in .rodata) but their modules have no cLight block.
LINKONCE_DROP = {
    # st3.cpp: only st3_3 keeps st3_checkCountDown, the caller of the header inline CountDown::checkState.
    # st3_0/st3_1 dropped the inline's body; st3_2 kept it as a nameless 0x18 tail (.text+0x888), like st3_3.
    "st3_0/st3.cpp": ["checkState__9CountDownUl"],
    "st3_1/st3.cpp": ["checkState__9CountDownUl"],
    "wep17/wep17.cpp": [
        "log__t8cManager1Z6cLightPCce",
        "countActiveWork__t8cManager1Z6cLight",
        "create__t8cManager1Z6cLighti",
        "create__t8cManager1Z6cLight",
        "create__t8cManager1Z6cLightiUl",
    ],
    "wep14/wep14.cpp": [
        "log__t8cManager1Z6cLightPCce",
        "countActiveWork__t8cManager1Z6cLight",
        "create__t8cManager1Z6cLighti",
        "create__t8cManager1Z6cLight",
        "create__t8cManager1Z6cLightiUl",
    ],
    # r22c.cpp includes light.h but the original object only carries the cManager<cObj>/<cEm> copies.
    "st2_4/r22c.cpp": [
        "log__t8cManager1Z6cLightPCce",
        "countActiveWork__t8cManager1Z6cLight",
        "create__t8cManager1Z6cLighti",
        "create__t8cManager1Z6cLight",
        "create__t8cManager1Z6cLightiUl",
    ],
}
