#!/usr/bin/env python3
"""REL plan step 2 (docs/port-boot.md): for ONE real REL module, generate the two small files a
statically-linked module needs that no vendor source provides --

  <out-dir>/section.h: `#pragma clang section data/bss/rodata=...` into three sections named after
  the module (`__DATA,__r_<mod>_d` / `__r_<mod>_b` / `__r_<mod>_ro` -- short because Mach-O caps a
  section name at 16 characters total, `mach-o section specifier requires a section whose length is
  between 1 and 16 characters`, confirmed the hard way with the obvious `__rel_<mod>_rodata` name for
  any module name over 6 characters), force-included
  (`-include`) into every one of the module's own TUs the same way include/port/game_section.h is
  force-included into every DOL TU (docs/port-boot.md section 40) -- so the module's globals land in
  their own named Mach-O sections instead of the conventional `__DATA,__data`/`__bss`, which ld64
  always places ahead of ANY custom section regardless of link order (the exact bug
  `src/port/arena.cpp`'s `__re4gdata`/`__re4gbss` fix this same way). Deliberately `__DATA,...` for
  ALL THREE, including rodata (not the usual `__TEXT,__const`): rodata needs a valid GC32() address
  in the same [lowmem, arena) window as data/bss too (a REL's `.rodata` can hold a raw pointer the
  game treats as a GameCube address, e.g. a static const table another struct points at), which only
  holds inside `__DATA` here (mirrors src/port/arena.cpp's "GC-faithful layout" ordering mechanism,
  which only works for sections in the same segment as `__re4low`).

  <out-dir>/desc.cpp: builds one `re4_port::RelModuleDesc` (include/port/rel_module.h) from
  config/G4BE08/modules/<mod>/rel.json (module_id, name) plus this module's own `_prolog`/`_epilog`/
  `_unresolved` (every stage/room module's own copy, e.g. src/st1/st1.cpp) and the three section
  bounds above (found at runtime with `getsectiondata()`, the same mechanism
  `src/port/arena.cpp::CheckGameSection` already uses for the DOL's own sections -- Mach-O has no
  ELF-style automatic `__start_<section>` symbols). Exposed through exactly one `extern "C"`
  accessor, `<Mod>_GetModuleDesc()` -- the ONLY symbol CMakeLists.txt's two-phase `ld -r` step
  exports from the module's combined, visibility-restricted object; every vendor symbol the module
  itself defines (`_prolog` above all -- EVERY module's own st1.cpp/st2.cpp/... copy defines a
  function by that exact name) gets hidden by that same step, since linking two modules' `_prolog`
  into the same final executable would otherwise collide. See CMakeLists.txt's `RE4_REL_MODULES`
  block for the two `ld -r` invocations this feeds.

Usage: python3 tools/port/gen_rel_module.py <mod> --out-dir <dir>
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

SECTION_H_TEMPLATE = """\
// GENERATED by tools/port/gen_rel_module.py for module {mod} -- do not edit by hand.
// Force-included (-include, CMakeLists.txt) into every TU of this module, first (before
// ptr32.h/layout_asserts.h), same convention as include/port/game_section.h for the DOL.
#ifndef RE4_PORT_REL_{MOD}_SECTION_H
#define RE4_PORT_REL_{MOD}_SECTION_H

#ifdef TARGET_PC
#pragma clang section data="__DATA,__r_{mod}_d"
#pragma clang section bss="__DATA,__r_{mod}_b"
#pragma clang section rodata="__DATA,__r_{mod}_ro"
#endif

#endif // RE4_PORT_REL_{MOD}_SECTION_H
"""

DESC_CPP_TEMPLATE = """\
// GENERATED by tools/port/gen_rel_module.py for module {mod} -- do not edit by hand.
// See this generator's own header comment for why exactly one symbol below stays exported.
#include "section.h"

#include "port/rel_module.h"

#include <mach-o/getsect.h>
#include <mach-o/ldsyms.h>

// This module's own copy (src/st1/st1.cpp and its st2/st4 counterparts, docs/unit-notes.md) --
// `extern "C"` already in the vendor source, so no linkage mismatch redeclaring it here.
extern "C" void _prolog();
extern "C" void _epilog();
extern "C" void _unresolved();

// _ctors/_dtors: on the real GameCube, the SN REL linker script populates these two NULL-terminated
// arrays from whichever of THIS module's own translation units have real C++ static objects with
// non-trivial constructors/destructors (st1.cpp's own _prolog/_epilog walk them, docs/matching.md).
// Empty here -- clang/LLVM on this host does not use that legacy GCC ctors-array ABI at all for its
// own static initializers (it emits `__DATA,__mod_init_func`, processed automatically by dyld for a
// normal executable, which a `ld -r` relocatable object like this module's own combine never is) --
// so there is no straightforward way yet to populate this array from what this module's own units
// actually need initialized. TO VERIFY (next slice, if a module with a real static-object
// constructor turns up): whether that gap ever matters here -- st1_0's own units (em_wrap.cpp,
// r100.cpp, r120.cpp) were only checked well enough to link, not proven free of such constructors.
void (*_ctors[])(void) = {{nullptr}};
void (*_dtors[])(void) = {{nullptr}};

namespace re4_port {{

static void* SectionStart(const char* sectname, std::size_t* size)
{{
    unsigned long sz = 0;
    void* p = getsectiondata(&_mh_execute_header, "__DATA", sectname, &sz);
    *size = sz;
    return p;
}}

extern "C" const RelModuleDesc* {Mod}_GetModuleDesc()
{{
    static RelModuleDesc desc = [] {{
        RelModuleDesc d{{}};
        d.id = {module_id};
        d.name = "{mod}";
        d.prolog = &_prolog;
        d.epilog = &_epilog;
        d.unresolved = &_unresolved;
        d.dataStart = SectionStart("__r_{mod}_d", &d.dataSize);
        d.bssStart = SectionStart("__r_{mod}_b", &d.bssSize);
        d.rodataStart = SectionStart("__r_{mod}_ro", &d.rodataSize);
        return d;
    }}();
    return &desc;
}}

}} // namespace re4_port
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("module")
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    mod = args.module
    rel_json_path = ROOT / "config" / "G4BE08" / "modules" / mod / "rel.json"
    if not rel_json_path.exists():
        print(f"gen_rel_module.py: no {rel_json_path}", file=sys.stderr)
        sys.exit(1)
    rel = json.loads(rel_json_path.read_text())

    # A valid C++ identifier component: modules.py/config.yml names are already `[A-Za-z0-9_]+`
    # (st1_0, wep02, Sscrn, ...) so this is just a capitalize, not a real sanitizer.
    mod_ident = mod[0].upper() + mod[1:]

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "section.h").write_text(
        SECTION_H_TEMPLATE.format(mod=mod, MOD=mod.upper()))
    (out_dir / "desc.cpp").write_text(
        DESC_CPP_TEMPLATE.format(mod=mod, Mod=mod_ident, module_id=rel["module_id"]))


if __name__ == "__main__":
    main()
