#!/usr/bin/env python3
"""Generates one small .cpp that registers every statically-linked REL module's descriptor
(`<Mod>_GetModuleDesc()`, tools/port/gen_rel_module.py) with re4_port's OSLink/OSUnlink registry
(include/port/rel.h's RegisterRelModule()), so src/port/boot_main.cpp's single
`re4_port::RegisterBuiltRelModules()` call stays correct as CMakeLists.txt's RE4_REL_MODULES list
grows, with nothing to hand-edit here.

Usage: python3 tools/port/gen_rel_registry.py <mod> [<mod> ...] --out <file.cpp>
"""
import argparse
from pathlib import Path

TEMPLATE = """\
// GENERATED by tools/port/gen_rel_registry.py for RE4_REL_MODULES = {mods} -- do not edit by hand.
#ifdef TARGET_PC

#include "port/rel.h"
#include "port/rel_module.h"

namespace re4_port {{

extern "C" {{
{externs}
}} // extern "C"

void RegisterBuiltRelModules()
{{
{calls}
}}

}} // namespace re4_port

#endif // TARGET_PC
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("modules", nargs="*")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    externs = []
    calls = []
    for mod in args.modules:
        # Same capitalize-only rule as gen_rel_module.py's own `mod_ident`.
        ident = mod[0].upper() + mod[1:]
        externs.append(f"const RelModuleDesc* {ident}_GetModuleDesc();")
        calls.append(f"    RegisterRelModule({ident}_GetModuleDesc());")

    Path(args.out).write_text(TEMPLATE.format(
        mods=" ".join(args.modules) if args.modules else "(none)",
        externs="\n".join(externs),
        calls="\n".join(calls) if calls else "    // RE4_REL_MODULES is empty -- nothing to register yet",
    ))


if __name__ == "__main__":
    main()
