#!/usr/bin/env python3
"""Best-effort stub generator for re4_boot's undefined-symbol list (docs/port.md "First boot").

Reads a linker undefined-symbol list (one Mach-O symbol per line, e.g. "_ActBtn", leading
underscore included) and, for each, greps include/*.h and src/game/*.h for a plausible C++
declaration (an `extern <Type> Name;`-shaped global, or a `<RetType> Name(...)`-shaped function
prototype). Emits:
  - a real definition (default-constructed) for a data symbol whose type looks default-constructible
  - a logging stub (prints the symbol name once via a static bool, returns a default value) for a
    function symbol
  - nothing, with a comment, for anything the heuristic can't confidently classify -- flagged in a
    companion report rather than guessed at, matching this repo's cast-rewriter precedent.

This is a heuristic text-based tool, not a real parser: every generated declaration should be spot-
checked against the header it was read from before trusting it, the same way the cast rewriter's
own output is spot-checked. Run:

    python3 tools/port/gen_boot_stubs.py /tmp/undef_syms.txt > src/port/stubs/generated_stubs.cpp
"""
import re
import sys

DECL_DIRS = ["include", "src/game"]


def find_declaration(name, root):
    import subprocess
    try:
        out = subprocess.check_output(
            ["grep", "-rhn", rf"\b{re.escape(name)}\b", "--include=*.h"] + DECL_DIRS,
            cwd=root, text=True)
    except subprocess.CalledProcessError:
        return []
    lines = []
    for line in out.splitlines():
        # line format: path:lineno:content
        parts = line.split(":", 2)
        if len(parts) < 3:
            continue
        content = parts[2].strip()
        if content.startswith("//") or content.startswith("*"):
            continue
        lines.append(content)
    return lines


FUNC_RE = re.compile(r"^(?:extern\s+)?([A-Za-z_][\w:<>* ]*?[\*&]?)\s+(\w+)\s*\(([^;]*)\)\s*;?\s*$")
DATA_RE = re.compile(r"^extern\s+([A-Za-z_][\w:<>]*(?:\s*\*)?)\s+(\w+)\s*(\[[^\]]*\])?\s*;\s*$")


def classify(name, decls):
    for d in decls:
        d = d.strip()
        if not d.startswith("extern") and "(" not in d:
            continue
        m = DATA_RE.match(d)
        if m and m.group(2) == name:
            return ("data", m.group(1).strip(), m.group(3) or "")
        m = FUNC_RE.match(d)
        if m and m.group(2) == name:
            return ("func", m.group(1).strip(), m.group(3))
    return (None, None, None)


DEFAULT_RETURNS = {
    "void": "",
    "int": "return 0;",
    "u32": "return 0;",
    "s32": "return 0;",
    "u16": "return 0;",
    "s16": "return 0;",
    "u8": "return 0;",
    "s8": "return 0;",
    "f32": "return 0.0f;",
    "BOOL": "return 0;",
    "bool": "return false;",
}


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 1
    root = "/Users/luken/Projects/re4"
    syms = [l.strip().lstrip("_") for l in open(sys.argv[1]) if l.strip()]

    print("// AUTO-GENERATED by tools/port/gen_boot_stubs.py -- see that file's header for the")
    print("// heuristic and its limits. Spot-check before trusting; this is a first attempt, not a")
    print("// verified-correct stub set.")
    print("#ifdef TARGET_PC")
    print('#include "types.h"')
    print("#include <cstdio>")
    print()
    print('extern "C" {')

    unresolved = []
    for name in syms:
        if not name or not re.match(r"^\w+$", name):
            continue
        decls = find_declaration(name, root)
        kind, ty, rest = classify(name, decls)
        if kind == "func":
            ret = ty
            body = DEFAULT_RETURNS.get(ret, f"return ({ret}) 0;" if ret not in ("", "void") else "")
            print(f"// {name}: heuristically matched `{ty} {name}({rest})`")
            print(f'{ret} {name}({rest})')
            print("{")
            print(f'    static bool warned = false;')
            print(f'    if (!warned) {{ std::fprintf(stderr, "STUB: {name}() called\\n"); warned = true; }}')
            if body:
                print(f"    {body}")
            print("}")
        else:
            unresolved.append(name)
            print(f"// UNRESOLVED (no confident C-linkage function match): {name}"
                  + (f" -- candidate decls: {decls[:2]}" if decls else " -- no declaration found"))

    print("} // extern \"C\"")
    print("#endif // TARGET_PC")

    if unresolved:
        print(f"// {len(unresolved)} unresolved symbols (likely C++ typed globals -- data, not "
              f"function -- or something this heuristic's regexes don't match): "
              + ", ".join(unresolved[:40]) + ("..." if len(unresolved) > 40 else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
