#!/usr/bin/env python3
"""Phase 2 step 5 (docs/port-phase2.md): generates host static_asserts of offsetof() for the
on-disc structs converted to Ptr32<T> under TARGET_PC, from their `// 0xNN` offset comments (the
same comments the rest of this decompilation already trusts as ground truth for every other
matching check). Read-only: writes build-pc/gen/port_static_asserts.cpp, never touches src/ or
include/.

A field's offset must be the same whether it is a T* (non-TARGET_PC) or a Ptr32<T> (TARGET_PC,
always exactly 4 bytes) -- that is the whole point of Ptr32<T> -- so one static_assert per field,
compiled only under TARGET_PC, is enough to catch either branch drifting from the other or from the
documented offset.

Usage: tools/port/gen_static_asserts.py > build-pc/gen/port_static_asserts.cpp
       (wired into CMakeLists.txt's re4_port_static_asserts target)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

# (header, struct name, extra #include needed for a forward-declared member type)
STRUCTS = [
    ("include/model.h", "cModelData", None),
    ("include/tpl.h", "CLUTHeader", None),
    ("include/tpl.h", "TEXHeader", None),
    ("include/tpl.h", "TEXDescriptor", None),
    ("include/tpl.h", "TEXPalette", None),
    ("include/cam_ctrl.h", "CameraAreaInfo", None),
    ("include/cam_ctrl.h", "CameraAreaRec", None),
    ("include/cam_ctrl.h", "CameraCut", None),
    ("include/game.h", "SAVE_DATA_HEAD", None),
    ("include/room_jmp.h", "CRoomInfo", None),
    ("include/atari.h", "cSatBlock", None),
]

# Structs defined inside a .cpp rather than a shared header (Phase 3, docs/port-phase3.md): can't
# be #include'd standalone (the .cpp pulls in its own translation unit's worth of other headers),
# so these get their own tiny extracted-body redeclaration instead of an #include line. (source
# file, struct name) -- the struct body is copied verbatim out of the source file, not re-derived,
# so it stays honest to whatever the source actually says.
INLINE_STRUCTS = [
    ("src/game/mes.cpp", "MesFontFile"),
]

# Matches "<type> <name>[array];  // 0xNN ...", tolerant of the repo's inconsistent spacing.
FIELD_RE = re.compile(r'^\s*[\w:<>*&,\s]+?\s([A-Za-z_]\w*)(?:\[[^\]]*\])?\s*;\s*//\s*(0x[0-9A-Fa-f]+)')


def extract_struct_body(text: str, struct_name: str) -> str:
    # Finds "struct NAME {" or "struct NAME : ... {" (first match after any #ifdef branches; field
    # offsets are identical in both, so either copy of the struct works) and returns the body up to
    # the matching close brace.
    m = re.search(r'\b(?:struct|class)\s+' + re.escape(struct_name) + r'\b[^{;]*\{', text)
    if not m:
        sys.exit(f"struct/class {struct_name} not found")
    depth = 1
    i = m.end()
    start = i
    while depth > 0:
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
        i += 1
    return text[start:i - 1]


def fields_of(body: str):
    seen = {}
    for line in body.splitlines():
        line = line.strip()
        if line.startswith('#'):
            continue
        m = FIELD_RE.match(line)
        if m:
            name, off = m.group(1), m.group(2)
            seen.setdefault(name, off)  # first occurrence (either #ifdef branch) wins
    return seen


def main():
    print("// Generated by tools/port/gen_static_asserts.py -- do not edit by hand.")
    print("// Phase 2 step 5 (docs/port-phase2.md): offsetof() checks for every Ptr32<T>-converted")
    print("// on-disc struct, from the header's own \"// 0xNN\" comments.")
    print("#ifndef TARGET_PC")
    print('#error "generated for TARGET_PC only"')
    print("#endif")
    print()
    includes = sorted({h for h, _, _ in STRUCTS})
    for h in includes:
        print(f'#include "{h[len("include/"):]}"')
    print()
    print("#include <cstddef>")
    print()
    for source, struct_name in INLINE_STRUCTS:
        text = (ROOT / source).read_text()
        body = extract_struct_body(text, struct_name)
        print(f"// {struct_name} (extracted verbatim from {source})")
        print(f"struct {struct_name} {{{body}}};")
        print()
    total = 0
    all_structs = [(h, n) for h, n, _ in STRUCTS] + INLINE_STRUCTS
    for header, struct_name, _ in STRUCTS:
        text = (ROOT / header).read_text()
        body = extract_struct_body(text, struct_name)
        fields = fields_of(body)
        if not fields:
            sys.exit(f"no \"// 0xNN\" fields found for struct {struct_name} in {header}")
        print(f"// {struct_name} ({header}, {len(fields)} fields)")
        for name, off in fields.items():
            print(f'static_assert(offsetof({struct_name}, {name}) == {off}, '
                  f'"{struct_name}::{name} must stay at {off}");')
            total += 1
        print()
    for source, struct_name in INLINE_STRUCTS:
        text = (ROOT / source).read_text()
        body = extract_struct_body(text, struct_name)
        fields = fields_of(body)
        if not fields:
            sys.exit(f"no \"// 0xNN\" fields found for struct {struct_name} in {source}")
        print(f"// {struct_name} ({source}, {len(fields)} fields, inline-extracted)")
        for name, off in fields.items():
            print(f'static_assert(offsetof({struct_name}, {name}) == {off}, '
                  f'"{struct_name}::{name} must stay at {off}");')
            total += 1
        print()
    print(f"// {total} offsetof() checks across {len(all_structs)} structs.")
    print("int main() { return 0; }")


if __name__ == "__main__":
    main()
