// AUTO-GENERATED by tools/port/gen_boot_stubs.py -- spot-check before trusting.
#ifdef TARGET_PC
#include "stub_common.h"

extern "C" {
// __builtin_delete: `void __builtin_delete(void* p)`
void __builtin_delete(void* p)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: __builtin_delete() called\n"); warned = true; }
}
// __builtin_new: `void* __builtin_new(unsigned int size)`
void* __builtin_new(unsigned int size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: __builtin_new() called\n"); warned = true; }
    return (void*) 0;
}
// __builtin_vec_delete: `void __builtin_vec_delete(void* p)`
void __builtin_vec_delete(void* p)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: __builtin_vec_delete() called\n"); warned = true; }
}
// __builtin_vec_new: `void* __builtin_vec_new(unsigned int size)`
void* __builtin_vec_new(unsigned int size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: __builtin_vec_new() called\n"); warned = true; }
    return (void*) 0;
}
// AddSandPower: `void AddSandPower(Vec& pos, f32 power)`
void AddSandPower(Vec& pos, f32 power)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AddSandPower() called\n"); warned = true; }
}
// AddWaterPower: `void AddWaterPower(Vec& pos, f32 power)`
void AddWaterPower(Vec& pos, f32 power)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AddWaterPower() called\n"); warned = true; }
}
// ADXGC_SetupDvdFs: `void ADXGC_SetupDvdFs(int mode)`
void ADXGC_SetupDvdFs(int mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ADXGC_SetupDvdFs() called\n"); warned = true; }
}
// ADXM_ExecMain: `void ADXM_ExecMain()`
void ADXM_ExecMain()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ADXM_ExecMain() called\n"); warned = true; }
}
// UNRESOLVED: ADXM_SetCbErr -- candidates: ['void ADXM_SetCbErr(void (*func)(void* obj, const char* msg), void* obj);', 'ADXM_SetCbErr(ap_mwply_err_func, NULL);']
// ADXT_SetOutputMono: `void ADXT_SetOutputMono(int sw)`
void ADXT_SetOutputMono(int sw)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ADXT_SetOutputMono() called\n"); warned = true; }
}
// AIInit: `void AIInit(u8* stack)`
void AIInit(u8* stack)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AIInit() called\n"); warned = true; }
}
// AIReset: `void AIReset(void)`
void AIReset(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AIReset() called\n"); warned = true; }
}
// ARGetBaseAddress: `u32 ARGetBaseAddress(void)`
u32 ARGetBaseAddress(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ARGetBaseAddress() called\n"); warned = true; }
    return 0;
}
// ARQFlushQueue: `void ARQFlushQueue(void)`
void ARQFlushQueue(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ARQFlushQueue() called\n"); warned = true; }
}
// At_em_rect_rect_ck: `u32 At_em_rect_rect_ck(cModel* pMod, cModel* pMod2)`
u32 At_em_rect_rect_ck(cModel* pMod, cModel* pMod2)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: At_em_rect_rect_ck() called\n"); warned = true; }
    return 0;
}
// UNRESOLVED: AXAcquireVoice -- candidates: ['AXVPB* AXAcquireVoice(u32 priority, void (*callback)(void *), u32 userContext);', 'axv->voice = AXAcquireVoice(30, cb_drop_voice, 0);']
// AXARTInit: `void AXARTInit(void)`
void AXARTInit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXARTInit() called\n"); warned = true; }
}
// AXARTQuit: `void AXARTQuit(void)`
void AXARTQuit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXARTQuit() called\n"); warned = true; }
}
// AXARTServiceSounds: `void AXARTServiceSounds(void)`
void AXARTServiceSounds(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXARTServiceSounds() called\n"); warned = true; }
}
// AXFreeVoice: `void AXFreeVoice(AXVPB* p)`
void AXFreeVoice(AXVPB* p)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFreeVoice() called\n"); warned = true; }
}
// AXFXChorusCallback: `void AXFXChorusCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_CHORUS* chorus)`
void AXFXChorusCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_CHORUS* chorus)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXChorusCallback() called\n"); warned = true; }
}
// AXFXChorusInit: `int AXFXChorusInit(AXFX_CHORUS* c)`
int AXFXChorusInit(AXFX_CHORUS* c)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXChorusInit() called\n"); warned = true; }
    return 0;
}
// AXFXChorusSettings: `int AXFXChorusSettings(AXFX_CHORUS* c)`
int AXFXChorusSettings(AXFX_CHORUS* c)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXChorusSettings() called\n"); warned = true; }
    return 0;
}
// AXFXChorusShutdown: `int AXFXChorusShutdown(AXFX_CHORUS* c)`
int AXFXChorusShutdown(AXFX_CHORUS* c)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXChorusShutdown() called\n"); warned = true; }
    return 0;
}
// AXFXDelayCallback: `void AXFXDelayCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_DELAY* delay)`
void AXFXDelayCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_DELAY* delay)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXDelayCallback() called\n"); warned = true; }
}
// AXFXDelayInit: `int AXFXDelayInit(AXFX_DELAY* delay)`
int AXFXDelayInit(AXFX_DELAY* delay)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXDelayInit() called\n"); warned = true; }
    return 0;
}
// AXFXDelaySettings: `int AXFXDelaySettings(AXFX_DELAY* delay)`
int AXFXDelaySettings(AXFX_DELAY* delay)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXDelaySettings() called\n"); warned = true; }
    return 0;
}
// AXFXDelayShutdown: `int AXFXDelayShutdown(AXFX_DELAY* delay)`
int AXFXDelayShutdown(AXFX_DELAY* delay)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXDelayShutdown() called\n"); warned = true; }
    return 0;
}
// AXFXReverbHiCallback: `void AXFXReverbHiCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_REVERBHI* reverb)`
void AXFXReverbHiCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_REVERBHI* reverb)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiCallback() called\n"); warned = true; }
}
// AXFXReverbHiCallbackDpl2: `void AXFXReverbHiCallbackDpl2(AXFX_BUFFERUPDATE_DPL2* bufferUpdate, AXFX_REVERBHI_DPL2* reverb)`
void AXFXReverbHiCallbackDpl2(AXFX_BUFFERUPDATE_DPL2* bufferUpdate, AXFX_REVERBHI_DPL2* reverb)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiCallbackDpl2() called\n"); warned = true; }
}
// AXFXReverbHiInit: `int AXFXReverbHiInit(AXFX_REVERBHI* rev)`
int AXFXReverbHiInit(AXFX_REVERBHI* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiInit() called\n"); warned = true; }
    return 0;
}
// AXFXReverbHiInitDpl2: `int AXFXReverbHiInitDpl2(AXFX_REVERBHI_DPL2* reverb)`
int AXFXReverbHiInitDpl2(AXFX_REVERBHI_DPL2* reverb)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiInitDpl2() called\n"); warned = true; }
    return 0;
}
// AXFXReverbHiSettings: `int AXFXReverbHiSettings(AXFX_REVERBHI* rev)`
int AXFXReverbHiSettings(AXFX_REVERBHI* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiSettings() called\n"); warned = true; }
    return 0;
}
// AXFXReverbHiSettingsDpl2: `int AXFXReverbHiSettingsDpl2(AXFX_REVERBHI_DPL2* rev)`
int AXFXReverbHiSettingsDpl2(AXFX_REVERBHI_DPL2* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiSettingsDpl2() called\n"); warned = true; }
    return 0;
}
// AXFXReverbHiShutdown: `int AXFXReverbHiShutdown(AXFX_REVERBHI* rev)`
int AXFXReverbHiShutdown(AXFX_REVERBHI* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiShutdown() called\n"); warned = true; }
    return 0;
}
// AXFXReverbHiShutdownDpl2: `int AXFXReverbHiShutdownDpl2(AXFX_REVERBHI_DPL2* reverb)`
int AXFXReverbHiShutdownDpl2(AXFX_REVERBHI_DPL2* reverb)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbHiShutdownDpl2() called\n"); warned = true; }
    return 0;
}
// AXFXReverbStdCallback: `void AXFXReverbStdCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_REVERBSTD* reverb)`
void AXFXReverbStdCallback(AXFX_BUFFERUPDATE* bufferUpdate, AXFX_REVERBSTD* reverb)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbStdCallback() called\n"); warned = true; }
}
// AXFXReverbStdInit: `int AXFXReverbStdInit(AXFX_REVERBSTD* rev)`
int AXFXReverbStdInit(AXFX_REVERBSTD* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbStdInit() called\n"); warned = true; }
    return 0;
}
// AXFXReverbStdSettings: `int AXFXReverbStdSettings(AXFX_REVERBSTD* rev)`
int AXFXReverbStdSettings(AXFX_REVERBSTD* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbStdSettings() called\n"); warned = true; }
    return 0;
}
// AXFXReverbStdShutdown: `int AXFXReverbStdShutdown(AXFX_REVERBSTD* rev)`
int AXFXReverbStdShutdown(AXFX_REVERBSTD* rev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXFXReverbStdShutdown() called\n"); warned = true; }
    return 0;
}
// UNRESOLVED: AXFXSetHooks -- candidates: ['void AXFXSetHooks(void* (*alloc)(u32), void (*free)(void*));', 'AXFXSetHooks(reverb_mem_alloc, Mem_free);']
// AXGetDspCycles: `u32 AXGetDspCycles(void)`
u32 AXGetDspCycles(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXGetDspCycles() called\n"); warned = true; }
    return 0;
}
// AXGetMaxDspCycles: `u32 AXGetMaxDspCycles(void)`
u32 AXGetMaxDspCycles(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXGetMaxDspCycles() called\n"); warned = true; }
    return 0;
}
// AXInitEx: `void AXInitEx(u32 outputBufferMode)`
void AXInitEx(u32 outputBufferMode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXInitEx() called\n"); warned = true; }
}
// AXQuit: `void AXQuit(void)`
void AXQuit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXQuit() called\n"); warned = true; }
}
// UNRESOLVED: AXRegisterAuxACallback -- candidates: ['void AXRegisterAuxACallback(void (*callback)(void*, void*), void* context);', 'AXRegisterAuxACallback(NULL, NULL);']
// UNRESOLVED: AXRegisterAuxBCallback -- candidates: ['void AXRegisterAuxBCallback(void (*callback)(void*, void*), void* context);', 'AXRegisterAuxBCallback(NULL, NULL);']
// AXRegisterCallback: `AXCallback AXRegisterCallback(AXCallback callback)`
AXCallback AXRegisterCallback(AXCallback callback)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXRegisterCallback() called\n"); warned = true; }
    return (AXCallback) 0;
}
// AXSetCompressor: `void AXSetCompressor(u32 switch_)`
void AXSetCompressor(u32 switch_)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetCompressor() called\n"); warned = true; }
}
// AXSetMode: `void AXSetMode(u32 mode)`
void AXSetMode(u32 mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetMode() called\n"); warned = true; }
}
// AXSetVoiceAddr: `void AXSetVoiceAddr(AXVPB* p, AXPBADDR* addr)`
void AXSetVoiceAddr(AXVPB* p, AXPBADDR* addr)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceAddr() called\n"); warned = true; }
}
// AXSetVoiceAdpcm: `void AXSetVoiceAdpcm(AXVPB* p, AXPBADPCM* adpcm)`
void AXSetVoiceAdpcm(AXVPB* p, AXPBADPCM* adpcm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceAdpcm() called\n"); warned = true; }
}
// AXSetVoiceAdpcmLoop: `void AXSetVoiceAdpcmLoop(AXVPB* p, AXPBADPCMLOOP* adpcmloop)`
void AXSetVoiceAdpcmLoop(AXVPB* p, AXPBADPCMLOOP* adpcmloop)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceAdpcmLoop() called\n"); warned = true; }
}
// AXSetVoiceEndAddr: `void AXSetVoiceEndAddr(AXVPB* p, u32 addr)`
void AXSetVoiceEndAddr(AXVPB* p, u32 addr)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceEndAddr() called\n"); warned = true; }
}
// AXSetVoiceLoop: `void AXSetVoiceLoop(AXVPB* p, u16 loop)`
void AXSetVoiceLoop(AXVPB* p, u16 loop)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceLoop() called\n"); warned = true; }
}
// AXSetVoiceLoopAddr: `void AXSetVoiceLoopAddr(AXVPB* p, u32 addr)`
void AXSetVoiceLoopAddr(AXVPB* p, u32 addr)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceLoopAddr() called\n"); warned = true; }
}
// AXSetVoiceLpf: `void AXSetVoiceLpf(AXVPB* p, AXPBLPF* lpf)`
void AXSetVoiceLpf(AXVPB* p, AXPBLPF* lpf)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceLpf() called\n"); warned = true; }
}
// AXSetVoiceLpfCoefs: `void AXSetVoiceLpfCoefs(AXVPB* p, u16 a0, u16 b0)`
void AXSetVoiceLpfCoefs(AXVPB* p, u16 a0, u16 b0)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceLpfCoefs() called\n"); warned = true; }
}
// AXSetVoicePriority: `void AXSetVoicePriority(AXVPB* p, u32 priority)`
void AXSetVoicePriority(AXVPB* p, u32 priority)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoicePriority() called\n"); warned = true; }
}
// AXSetVoiceSrc: `void AXSetVoiceSrc(AXVPB* p, AXPBSRC* src_)`
void AXSetVoiceSrc(AXVPB* p, AXPBSRC* src_)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceSrc() called\n"); warned = true; }
}
// AXSetVoiceSrcRatio: `void AXSetVoiceSrcRatio(AXVPB* p, f32 ratio)`
void AXSetVoiceSrcRatio(AXVPB* p, f32 ratio)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceSrcRatio() called\n"); warned = true; }
}
// AXSetVoiceSrcType: `void AXSetVoiceSrcType(AXVPB* p, u32 type)`
void AXSetVoiceSrcType(AXVPB* p, u32 type)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceSrcType() called\n"); warned = true; }
}
// AXSetVoiceState: `void AXSetVoiceState(AXVPB* p, u16 state)`
void AXSetVoiceState(AXVPB* p, u16 state)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceState() called\n"); warned = true; }
}
// AXSetVoiceType: `void AXSetVoiceType(AXVPB* p, u16 type)`
void AXSetVoiceType(AXVPB* p, u16 type)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: AXSetVoiceType() called\n"); warned = true; }
}
// ClothInit: `void ClothInit()`
void ClothInit()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ClothInit() called\n"); warned = true; }
}
// ClothTexSetUp: `int ClothTexSetUp(void* tpl, GXTexObj* tex, int no, GXTlutObj* tlut)`
int ClothTexSetUp(void* tpl, GXTexObj* tex, int no, GXTlutObj* tlut)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ClothTexSetUp() called\n"); warned = true; }
    return 0;
}
// ClrShape: `void ClrShape(cModel* pMod)`
void ClrShape(cModel* pMod)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ClrShape() called\n"); warned = true; }
}
// CoreDataRead: real definition now in src/game/read.cpp (docs/port-boot.md section 35 -- read.cpp
// un-excluded from cmake/boot_exclude.txt, its Ptr32/pointer-cast issues turned out already handled
// by the RE4_REWRITE_CASTS cast rewriter).
// COSF: `f32 COSF(f32 x)`
f32 COSF(f32 x)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: COSF() called\n"); warned = true; }
    return 0.0f;
}
// DBIsDebuggerPresent: `BOOL DBIsDebuggerPresent(void)`
BOOL DBIsDebuggerPresent(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: DBIsDebuggerPresent() called\n"); warned = true; }
    return 0;
}
// de_Boor_Cox: `int de_Boor_Cox(int n, f32* p, f32 t, int order, f32* B)`
int de_Boor_Cox(int n, f32* p, f32 t, int order, f32* B)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: de_Boor_Cox() called\n"); warned = true; }
    return 0;
}
// DiedemoExec: `void DiedemoExec(int time, int type)`
void DiedemoExec(int time, int type)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: DiedemoExec() called\n"); warned = true; }
}
// Draw_box: `void Draw_box(Vec* pBoxVec, u32 col, int flg)`
void Draw_box(Vec* pBoxVec, u32 col, int flg)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_box() called\n"); warned = true; }
}
// Draw_corn2: `void Draw_corn2(Vec* pPos, Vec* pVec, f32 size, f32 r, u32 col)`
void Draw_corn2(Vec* pPos, Vec* pVec, f32 size, f32 r, u32 col)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_corn2() called\n"); warned = true; }
}
// Draw_cylinder: `void Draw_cylinder(Vec* pos, f32 r, f32 h, u32 rgba)`
void Draw_cylinder(Vec* pos, f32 r, f32 h, u32 rgba)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_cylinder() called\n"); warned = true; }
}
// Draw_line3d: `void Draw_line3d(Vec* p0, Vec* p1, u32 col, int blend)`
void Draw_line3d(Vec* p0, Vec* p1, u32 col, int blend)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_line3d() called\n"); warned = true; }
}
// Draw_line3d_local: `void Draw_line3d_local(Vec* p0, Vec* b, Mtx mat, u32 col, int blend)`
void Draw_line3d_local(Vec* p0, Vec* b, Mtx mat, u32 col, int blend)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_line3d_local() called\n"); warned = true; }
}
// Draw_local_pos: `void Draw_local_pos(Vec* pos, int size, Mtx mat)`
void Draw_local_pos(Vec* pos, int size, Mtx mat)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_local_pos() called\n"); warned = true; }
}
// Draw_poly: `void Draw_poly(Vec* p, u32 col, int zmode)`
void Draw_poly(Vec* p, u32 col, int zmode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_poly() called\n"); warned = true; }
}
// Draw_poly_local: `void Draw_poly_local(Vec* p, Mtx mat, u32 col, int zmode)`
void Draw_poly_local(Vec* p, Mtx mat, u32 col, int zmode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_poly_local() called\n"); warned = true; }
}
// Draw_pos: `void Draw_pos(Vec* pos, int size)`
void Draw_pos(Vec* pos, int size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_pos() called\n"); warned = true; }
}
// Draw_quad: `void Draw_quad(Vec* pPos, Vec* pSize, u32 col)`
void Draw_quad(Vec* pPos, Vec* pSize, u32 col)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_quad() called\n"); warned = true; }
}
// Draw_sphere: `void Draw_sphere(Vec* pos, f32 r, u32 rgb, int zmode, int zcheck)`
void Draw_sphere(Vec* pos, f32 r, u32 rgb, int zmode, int zcheck)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Draw_sphere() called\n"); warned = true; }
}
// DrawOba: `void DrawOba(cModel* pMod)`
void DrawOba(cModel* pMod)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: DrawOba() called\n"); warned = true; }
}
// EmAtCheck: `void EmAtCheck(cModel* pMod)`
void EmAtCheck(cModel* pMod)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: EmAtCheck() called\n"); warned = true; }
}
// EmHitCheck: `BOOL EmHitCheck(Vec* ret_cross, Vec* ret_norm, Vec* pos0, Vec* pos1, u32 flag)`
BOOL EmHitCheck(Vec* ret_cross, Vec* ret_norm, Vec* pos0, Vec* pos1, u32 flag)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: EmHitCheck() called\n"); warned = true; }
    return 0;
}
// EmReadInit / EmReadSearch: real definitions now in src/game/read.cpp (docs/port-boot.md
// section 35 continuation -- read.cpp un-excluded).
// EndPlDamage: `void EndPlDamage()`
void EndPlDamage()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: EndPlDamage() called\n"); warned = true; }
}
// EndSubDamage: `void EndSubDamage()`
void EndSubDamage()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: EndSubDamage() called\n"); warned = true; }
}
// Esp04_Trans: `void Esp04_Trans(cEsp* esp)`
void Esp04_Trans(cEsp* esp)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp04_Trans() called\n"); warned = true; }
}
// Esp08_Create: `cEsp* Esp08_Create()`
cEsp* Esp08_Create()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp08_Create() called\n"); warned = true; }
    return (cEsp*) 0;
}
// Esp08_Trans: `void Esp08_Trans(cEsp* esp)`
void Esp08_Trans(cEsp* esp)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp08_Trans() called\n"); warned = true; }
}
// Esp0a_Trans: `void Esp0a_Trans(cEsp* esp)`
void Esp0a_Trans(cEsp* esp)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp0a_Trans() called\n"); warned = true; }
}
// Esp12_Trans: `void Esp12_Trans(cEsp* esp)`
void Esp12_Trans(cEsp* esp)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp12_Trans() called\n"); warned = true; }
}
// Esp16_Trans: `void Esp16_Trans(cEsp* esp)`
void Esp16_Trans(cEsp* esp)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp16_Trans() called\n"); warned = true; }
}
// Espgen02_Move: `void Espgen02_Move(EspgenWork* pEspgen)`
void Espgen02_Move(EspgenWork* pEspgen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen02_Move() called\n"); warned = true; }
}
// UNRESOLVED: Espgen02_SetFreeWork -- candidates: ['int Espgen02_SetFreeWork(EspgenWork* w, EspGenWork* rec, EspSeqData* head, cModel* model, u16 parts, Mtx* mtx,', 'int Espgen02_SetFreeWork(EspgenWork* w, EspGenWork* rec, EspSeqData* head, cModel* model, u16 parts, Mtx* mtx,']
// Espgen42_Destruct: `void Espgen42_Destruct(EspgenWork* pGen)`
void Espgen42_Destruct(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen42_Destruct() called\n"); warned = true; }
}
// Espgen42_Move: `void Espgen42_Move(EspgenWork* pGen)`
void Espgen42_Move(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen42_Move() called\n"); warned = true; }
}
// UNRESOLVED: Espgen42_SetFreeWork -- candidates: ['int Espgen42_SetFreeWork(EspgenWork* w, EspGenWork* rec, EspSeqData* head, cModel* model, u16 parts, Mtx* mtx,', 'NULL, NULL, Espgen42_SetFreeWork, Espgen43_SetFreeWork, Espgen44_SetFreeWork, Espgen45_SetFreeWork,']
// Espgen42_Trans: `void Espgen42_Trans(EspgenWork* pGen)`
void Espgen42_Trans(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen42_Trans() called\n"); warned = true; }
}
// Espgen43_Destruct: `void Espgen43_Destruct(EspgenWork* pGen)`
void Espgen43_Destruct(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen43_Destruct() called\n"); warned = true; }
}
// Espgen43_Move: `void Espgen43_Move(EspgenWork* pGen)`
void Espgen43_Move(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen43_Move() called\n"); warned = true; }
}
// UNRESOLVED: Espgen43_SetFreeWork -- candidates: ['int Espgen43_SetFreeWork(EspgenWork* w, EspGenWork* rec, EspSeqData* head, cModel* model, u16 parts, Mtx* mtx,', 'NULL, NULL, Espgen42_SetFreeWork, Espgen43_SetFreeWork, Espgen44_SetFreeWork, Espgen45_SetFreeWork,']
// Espgen43_Trans: `void Espgen43_Trans(EspgenWork* pGen)`
void Espgen43_Trans(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen43_Trans() called\n"); warned = true; }
}
// Espgen45_Destruct: `void Espgen45_Destruct(EspgenWork* pGen)`
void Espgen45_Destruct(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen45_Destruct() called\n"); warned = true; }
}
// Espgen45_Move: `void Espgen45_Move(EspgenWork* pGen)`
void Espgen45_Move(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen45_Move() called\n"); warned = true; }
}
// UNRESOLVED: Espgen45_SetFreeWork -- candidates: ['int Espgen45_SetFreeWork(EspgenWork* w, EspGenWork* rec, EspSeqData* head, cModel* model, u16 parts, Mtx* mtx,', 'NULL, NULL, Espgen42_SetFreeWork, Espgen43_SetFreeWork, Espgen44_SetFreeWork, Espgen45_SetFreeWork,']
// Espgen45_Trans: `void Espgen45_Trans(EspgenWork* pGen)`
void Espgen45_Trans(EspgenWork* pGen)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Espgen45_Trans() called\n"); warned = true; }
}
// EspWaterInit: `void EspWaterInit()`
void EspWaterInit()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: EspWaterInit() called\n"); warned = true; }
}
// Estgen45SetColor: `void Estgen45SetColor(u8 r, u8 g, u8 b, u8 a, f32 sr, f32 sg, f32 sb, f32 sa)`
void Estgen45SetColor(u8 r, u8 g, u8 b, u8 a, f32 sr, f32 sg, f32 sb, f32 sa)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetColor() called\n"); warned = true; }
}
// Estgen45SetColorMul: `void Estgen45SetColorMul(int bTc)`
void Estgen45SetColorMul(int bTc)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetColorMul() called\n"); warned = true; }
}
// Estgen45SetColorOverWrite: `void Estgen45SetColorOverWrite(int bTc)`
void Estgen45SetColorOverWrite(int bTc)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetColorOverWrite() called\n"); warned = true; }
}
// Estgen45SetHeight: `void Estgen45SetHeight(f32 y)`
void Estgen45SetHeight(f32 y)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetHeight() called\n"); warned = true; }
}
// Estgen45SetParam: `void Estgen45SetParam(Esp4cWork* pFree)`
void Estgen45SetParam(Esp4cWork* pFree)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetParam() called\n"); warned = true; }
}
// Estgen45SetParamOverWrite: `void Estgen45SetParamOverWrite(int bTc)`
void Estgen45SetParamOverWrite(int bTc)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetParamOverWrite() called\n"); warned = true; }
}
// Estgen45SetSize: `void Estgen45SetSize(f32 size)`
void Estgen45SetSize(f32 size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetSize() called\n"); warned = true; }
}
// Estgen45SetSizeOverWrite: `void Estgen45SetSizeOverWrite(int bTc)`
void Estgen45SetSizeOverWrite(int bTc)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetSizeOverWrite() called\n"); warned = true; }
}
// Estgen45SetTargetCamera: `void Estgen45SetTargetCamera(int bTc)`
void Estgen45SetTargetCamera(int bTc)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetTargetCamera() called\n"); warned = true; }
}
// Estgen45SetTargetHeight: `void Estgen45SetTargetHeight(int bTc)`
void Estgen45SetTargetHeight(int bTc)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetTargetHeight() called\n"); warned = true; }
}
// Estgen45SetTargetPos: `void Estgen45SetTargetPos(f32 x, f32 z)`
void Estgen45SetTargetPos(f32 x, f32 z)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Estgen45SetTargetPos() called\n"); warned = true; }
}
// GameAddPoint: `void GameAddPoint(int type)`
void GameAddPoint(int type)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GameAddPoint() called\n"); warned = true; }
}
// GameContinue: `void GameContinue(int option_flag)`
void GameContinue(int option_flag)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GameContinue() called\n"); warned = true; }
}
// GameLoad: `void GameLoad()`
void GameLoad()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GameLoad() called\n"); warned = true; }
}
// GameTask: `void GameTask()`
void GameTask()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GameTask() called\n"); warned = true; }
}
// getChapterSection: `void getChapterSection(int no, int* chap, int* sect)`
void getChapterSection(int no, int* chap, int* sect)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: getChapterSection() called\n"); warned = true; }
}
// GetFree: `u32 GetFree(int no)`
u32 GetFree(int no)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GetFree() called\n"); warned = true; }
    return 0;
}
// GetPrimBuff: `void* GetPrimBuff(int size)`
void* GetPrimBuff(int size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GetPrimBuff() called\n"); warned = true; }
    return (void*) 0;
}
// GetSandHeight: `int GetSandHeight(Vec* pos, f32* Ret)`
int GetSandHeight(Vec* pos, f32* Ret)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GetSandHeight() called\n"); warned = true; }
    return 0;
}
// GetWepSizeGroup: `int GetWepSizeGroup(int wepId)`
int GetWepSizeGroup(int wepId)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GetWepSizeGroup() called\n"); warned = true; }
    return 0;
}
// GXSetCurrentGXThread: `OSThread* GXSetCurrentGXThread(void)`
OSThread* GXSetCurrentGXThread(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GXSetCurrentGXThread() called\n"); warned = true; }
    return (OSThread*) 0;
}
// UNRESOLVED: GXWGFifo -- candidates: ['extern volatile WGPipe GXWGFifo[];', 'GXWGFifo->f32 = x;']
// hermite: `f32 hermite(f32* x, f32* v, f32 t)`
f32 hermite(f32* x, f32* v, f32 t)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: hermite() called\n"); warned = true; }
    return 0.0f;
}
// IdSetNum: `void IdSetNum(IDSystem* pIdSys, int idmNo, u8 idcNo, int num, int max, int keta, int mode)`
void IdSetNum(IDSystem* pIdSys, int idmNo, u8 idcNo, int num, int max, int keta, int mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: IdSetNum() called\n"); warned = true; }
}
// init_dbmodule: `void init_dbmodule()`
void init_dbmodule()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: init_dbmodule() called\n"); warned = true; }
}
// LIMIT_ANGLE: `f32 LIMIT_ANGLE(f32 x)`
f32 LIMIT_ANGLE(f32 x)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: LIMIT_ANGLE() called\n"); warned = true; }
    return 0.0f;
}
// low_RotMatrix: `void low_RotMatrix(Mtx m, Vec* vec)`
void low_RotMatrix(Mtx m, Vec* vec)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: low_RotMatrix() called\n"); warned = true; }
}
// Matrix2AxisAngle: `void Matrix2AxisAngle(Mtx m, Vec* ang)`
void Matrix2AxisAngle(Mtx m, Vec* ang)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Matrix2AxisAngle() called\n"); warned = true; }
}
// memclr_asm: `void memclr_asm(void* dst, u32 n)`
// NOT a logging-only stub (docs/port-boot.md's stub audit, coordinator lead): a pure real-memory-
// operation asm-bodied unit (docs/port-boot.md section 4's asm-bodied-unit survey) that the
// generic stub generator treated like any other undefined symbol -- a one-time "STUB: ... called"
// marker with no actual effect. Every caller depends on the destination actually being cleared
// (e.g. `cDvd::pullReadQueue()`'s `memclr_asm(q, sizeof(cDvdQueue))` resetting a reused
// `cDvdQueue` slot's state machine -- docs/port-boot.md section 20's `m_Rno0`-stays-stale bug was
// this exact function doing nothing). Real semantics: zero-fill, same as `memset(dst, 0, n)`.
void memclr_asm(void* dst, u32 n)
{
    if (dst && n) {
        std::memset(dst, 0, n);
    }
}
// memset_asm: `void memset_asm(void* dst, int c, u32 n)`
// Same class of bug as memclr_asm above -- real semantics, `memset(dst, c, n)`.
void memset_asm(void* dst, int c, u32 n)
{
    if (dst && n) {
        std::memset(dst, c, n);
    }
}
// MercSysGetSaveWork: `void MercSysGetSaveWork(MercSaveWork* pSaveWk)`
void MercSysGetSaveWork(MercSaveWork* pSaveWk)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MercSysGetSaveWork() called\n"); warned = true; }
}
// MercSysSetAddTime: `int MercSysSetAddTime(int time)`
int MercSysSetAddTime(int time)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MercSysSetAddTime() called\n"); warned = true; }
    return 0;
}
// MercSysSetBonusTime: `int MercSysSetBonusTime(int time)`
int MercSysSetBonusTime(int time)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MercSysSetBonusTime() called\n"); warned = true; }
    return 0;
}
// MIXInit: `void MIXInit(void)`
void MIXInit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXInit() called\n"); warned = true; }
}
// MIXInitChannel: `void MIXInitChannel(AXVPB* axvpb, u32 mode, int input, int auxA, int auxB, int pan, int span, int fader)`
void MIXInitChannel(AXVPB* axvpb, u32 mode, int input, int auxA, int auxB, int pan, int span, int fader)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXInitChannel() called\n"); warned = true; }
}
// MIXQuit: `void MIXQuit(void)`
void MIXQuit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXQuit() called\n"); warned = true; }
}
// MIXReleaseChannel: `void MIXReleaseChannel(AXVPB* axvpb)`
void MIXReleaseChannel(AXVPB* axvpb)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXReleaseChannel() called\n"); warned = true; }
}
// MIXSetAuxA: `void MIXSetAuxA(AXVPB* p, int dB)`
void MIXSetAuxA(AXVPB* p, int dB)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXSetAuxA() called\n"); warned = true; }
}
// MIXSetAuxB: `void MIXSetAuxB(AXVPB* p, int dB)`
void MIXSetAuxB(AXVPB* p, int dB)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXSetAuxB() called\n"); warned = true; }
}
// MIXSetInput: `void MIXSetInput(AXVPB* p, int dB)`
void MIXSetInput(AXVPB* p, int dB)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXSetInput() called\n"); warned = true; }
}
// MIXSetPan: `void MIXSetPan(AXVPB* p, int pan)`
void MIXSetPan(AXVPB* p, int pan)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXSetPan() called\n"); warned = true; }
}
// MIXSetSoundMode: `void MIXSetSoundMode(u32 mode)`
void MIXSetSoundMode(u32 mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXSetSoundMode() called\n"); warned = true; }
}
// MIXSetSPan: `void MIXSetSPan(AXVPB* p, int span)`
void MIXSetSPan(AXVPB* p, int span)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXSetSPan() called\n"); warned = true; }
}
// MIXUpdateSettings: `void MIXUpdateSettings(void)`
void MIXUpdateSettings(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MIXUpdateSettings() called\n"); warned = true; }
}
// ModelTrans: `void ModelTrans(cModel* model)`
void ModelTrans(cModel* model)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ModelTrans() called\n"); warned = true; }
}
// MtxNNInverse: `f32 MtxNNInverse(int n, f32* m, f32* m_inv)`
f32 MtxNNInverse(int n, f32* m, f32* m_inv)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MtxNNInverse() called\n"); warned = true; }
    return 0.0f;
}
// MtxNNMultVecSR: `void MtxNNMultVecSR(int n, int m, f32* mat, f32* v, f32* v_dst)`
void MtxNNMultVecSR(int n, int m, f32* mat, f32* v, f32* v_dst)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MtxNNMultVecSR() called\n"); warned = true; }
}
// MtxRotAxisPosRad: `void MtxRotAxisPosRad(Mtx m, Vec* axis, Vec* pos, f32 rad)`
void MtxRotAxisPosRad(Mtx m, Vec* axis, Vec* pos, f32 rad)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: MtxRotAxisPosRad() called\n"); warned = true; }
}
// mwPlyCalcWorkCprmSfd: `int mwPlyCalcWorkCprmSfd(MWS_PLY_CPRM_SFD* prm)`
int mwPlyCalcWorkCprmSfd(MWS_PLY_CPRM_SFD* prm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyCalcWorkCprmSfd() called\n"); warned = true; }
    return 0;
}
// mwPlyCreateSofdec: `MWPLY mwPlyCreateSofdec(MWS_PLY_CPRM_SFD* prm)`
MWPLY mwPlyCreateSofdec(MWS_PLY_CPRM_SFD* prm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyCreateSofdec() called\n"); warned = true; }
    return (MWPLY) 0;
}
// mwPlyFxCnvFrmARGB8888: `void mwPlyFxCnvFrmARGB8888(MWPLY hn, MWS_FRM* frm, void* buf)`
void mwPlyFxCnvFrmARGB8888(MWPLY hn, MWS_FRM* frm, void* buf)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyFxCnvFrmARGB8888() called\n"); warned = true; }
}
// mwPlyFxCnvFrmY84C44: `void mwPlyFxCnvFrmY84C44(MWPLY hn, MWS_FRM* frm, void* ybuf, void* uvbuf)`
void mwPlyFxCnvFrmY84C44(MWPLY hn, MWS_FRM* frm, void* ybuf, void* uvbuf)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyFxCnvFrmY84C44() called\n"); warned = true; }
}
// mwPlyFxSetOutBufPitchHeight: `void mwPlyFxSetOutBufPitchHeight(MWPLY hn, int pitch, int height)`
void mwPlyFxSetOutBufPitchHeight(MWPLY hn, int pitch, int height)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyFxSetOutBufPitchHeight() called\n"); warned = true; }
}
// mwPlyFxSetOutBufSize: `void mwPlyFxSetOutBufSize(MWPLY hn, int width, int height)`
void mwPlyFxSetOutBufSize(MWPLY hn, int width, int height)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyFxSetOutBufSize() called\n"); warned = true; }
}
// mwPlyGetCurFrm: `void mwPlyGetCurFrm(MWPLY hn, MWS_FRM* frm)`
void mwPlyGetCurFrm(MWPLY hn, MWS_FRM* frm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyGetCurFrm() called\n"); warned = true; }
}
// mwPlyGetHdrInf: `void mwPlyGetHdrInf(void* buf, int size, MWS_SFD_HDRINF* info)`
void mwPlyGetHdrInf(void* buf, int size, MWS_SFD_HDRINF* info)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyGetHdrInf() called\n"); warned = true; }
}
// mwPlyGetNumSkipDec: `int mwPlyGetNumSkipDec(MWPLY hn)`
int mwPlyGetNumSkipDec(MWPLY hn)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyGetNumSkipDec() called\n"); warned = true; }
    return 0;
}
// mwPlyGetNumSkipDisp: `int mwPlyGetNumSkipDisp(MWPLY hn)`
int mwPlyGetNumSkipDisp(MWPLY hn)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyGetNumSkipDisp() called\n"); warned = true; }
    return 0;
}
// mwPlyInitSfdFx: `void mwPlyInitSfdFx(MWS_PLY_INIT_SFD* prm)`
void mwPlyInitSfdFx(MWS_PLY_INIT_SFD* prm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyInitSfdFx() called\n"); warned = true; }
}
// mwPlyRelCurFrm: `void mwPlyRelCurFrm(MWPLY hn)`
void mwPlyRelCurFrm(MWPLY hn)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: mwPlyRelCurFrm() called\n"); warned = true; }
}
// ObaLineHitChk: `BOOL ObaLineHitChk(cModel* m, cAtariInfo* info, const Vec& pos10, const Vec& pos11, Vec& hit, Vec& nrm)`
BOOL ObaLineHitChk(cModel* m, cAtariInfo* info, const Vec& pos10, const Vec& pos11, Vec& hit, Vec& nrm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ObaLineHitChk() called\n"); warned = true; }
    return 0;
}
// ObjHitCheck: `int ObjHitCheck(Vec* ret_cross, Vec* ret_norm, Vec* pos0, Vec* pos1, u32 flag)`
int ObjHitCheck(Vec* ret_cross, Vec* ret_norm, Vec* pos0, Vec* pos1, u32 flag)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ObjHitCheck() called\n"); warned = true; }
    return 0;
}
// OptionDataRead: real definition now in src/game/read.cpp (docs/port-boot.md section 35
// continuation -- read.cpp un-excluded).
// OSCancelThread: real semantics now in src/port/os_thread.cpp (docs/port-boot.md section 34).
// UNRESOLVED: OSCreateThread -- candidates: ['int OSCreateThread(OSThread* thread, void* (*func)(void*), void* param, void* stack, u32 stackSize, OSPriority priority, u16 attr);', 'OSCreateThread(&pT->Thread, pT->hook, (void*) pT->arg, pT->pStack, pT->StackSize, pT->Priority, 1);']
// OSDisableInterrupts: `BOOL OSDisableInterrupts(void)`
BOOL OSDisableInterrupts(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSDisableInterrupts() called\n"); warned = true; }
    return 0;
}
// OSEnableInterrupts: `BOOL OSEnableInterrupts(void)`
BOOL OSEnableInterrupts(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSEnableInterrupts() called\n"); warned = true; }
    return 0;
}
// OSEnableScheduler: `s32 OSEnableScheduler(void)`
s32 OSEnableScheduler(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSEnableScheduler() called\n"); warned = true; }
    return 0;
}
// OSExitThread: real semantics now in src/port/os_thread.cpp (docs/port-phase3.md's continuation --
// the scheduler.cpp task-thread rework).
// OSGetConsoleSimulatedMemSize: `u32 OSGetConsoleSimulatedMemSize(void)`
u32 OSGetConsoleSimulatedMemSize(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetConsoleSimulatedMemSize() called\n"); warned = true; }
    return 0;
}
// OSGetConsoleType: `u32 OSGetConsoleType(void)`
u32 OSGetConsoleType(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetConsoleType() called\n"); warned = true; }
    return 0;
}
// OSGetCurrentThread: real semantics now in src/port/os_thread.cpp.
// OSGetFontEncode: `u16 OSGetFontEncode(void)`
u16 OSGetFontEncode(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetFontEncode() called\n"); warned = true; }
    return 0;
}
// OSGetFontTexture: `char* OSGetFontTexture(const char* string, void** image, s32* x, s32* y, s32* width)`
char* OSGetFontTexture(const char* string, void** image, s32* x, s32* y, s32* width)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetFontTexture() called\n"); warned = true; }
    return (char*) 0;
}
// OSGetProgressiveMode: `u32 OSGetProgressiveMode()`
u32 OSGetProgressiveMode()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetProgressiveMode() called\n"); warned = true; }
    return 0;
}
// OSGetResetButtonState: `BOOL OSGetResetButtonState(void)`
BOOL OSGetResetButtonState(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetResetButtonState() called\n"); warned = true; }
    return 0;
}
// OSGetSoundMode: `u32 OSGetSoundMode(void)`
u32 OSGetSoundMode(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSGetSoundMode() called\n"); warned = true; }
    return 0;
}
// OSInitAlarm: `void OSInitAlarm(void)`
void OSInitAlarm(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSInitAlarm() called\n"); warned = true; }
}
// OSInitFont: `BOOL OSInitFont(OSFontHeader* fontData)`
BOOL OSInitFont(OSFontHeader* fontData)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSInitFont() called\n"); warned = true; }
    return 0;
}
// OSInitSemaphore: real semantics now in src/port/os_thread.cpp (docs/port-boot.md section 34 --
// built on the same OSSleepThread/OSWakeupThread the scheduler uses, modeled on src/lib/
// OSSemaphore.c).
// OSInitThreadQueue: real semantics now in src/port/os_thread.cpp.
// OSPanic: `void OSPanic(const char* file, int line, const char* msg, ...)`
// NOT a logging-only stub: a real OSPanic() call means the game itself detected a fatal condition
// (a failed ASSERTMSGLINE, scheduler.cpp's stack-overflow guard, ...) and never returns on real
// hardware -- letting it fall through to a no-op here means the caller's own code keeps running
// past a state the vendor explicitly decided was unrecoverable, which is worse than crashing
// (docs/port-phase3.md's stub-audit rule: a stub must have the real contract, not just log).
void OSPanic(const char* file, int line, const char* msg, ...)
{
    va_list ap;
    va_start(ap, msg);
    std::fprintf(stderr, "OSPanic: %s:%d: ", file, line);
    std::vfprintf(stderr, msg, ap);
    std::fprintf(stderr, "\n");
    va_end(ap);
    std::fflush(stderr);
    std::abort();
}
// OSReport: `void OSReport(const char* fmt, ...)`
// NOT a logging-only stub: a real vfprintf pass-through, not just a one-time call-site marker --
// this is the game's own diagnostic channel (`"DVD: Read File: %s"`, `"DVD: Read Ok "`, ...,
// src/game/dvd.cpp among many others) and losing every message behind a single "STUB: OSReport()
// called" line (the generic generated-stub shape) actively hid this session's own DVD-queue bug
// investigation (docs/port-boot.md section 20) -- high debugging value, no correctness risk either
// way (OSReport has no return value/output parameter callers depend on).
void OSReport(const char* fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    std::vfprintf(stderr, fmt, ap);
    va_end(ap);
}
// OSResetSystem: `void OSResetSystem(int reset, u32 resetCode, BOOL forceMenu)`
void OSResetSystem(int reset, u32 resetCode, BOOL forceMenu)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSResetSystem() called\n"); warned = true; }
}
// OSRestoreInterrupts: `BOOL OSRestoreInterrupts(BOOL level)`
BOOL OSRestoreInterrupts(BOOL level)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSRestoreInterrupts() called\n"); warned = true; }
    return 0;
}
// OSResumeThread: real semantics now in src/port/os_thread.cpp.
// OSSetErrorHandler: `OSErrorHandler OSSetErrorHandler(OSError error, OSErrorHandler handler)`
OSErrorHandler OSSetErrorHandler(OSError error, OSErrorHandler handler)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSSetErrorHandler() called\n"); warned = true; }
    return (OSErrorHandler) 0;
}
// OSSetProgressiveMode: `void OSSetProgressiveMode(u32 on)`
void OSSetProgressiveMode(u32 on)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSSetProgressiveMode() called\n"); warned = true; }
}
// OSSetSaveRegion: `void OSSetSaveRegion(void* start, void* end)`
void OSSetSaveRegion(void* start, void* end)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSSetSaveRegion() called\n"); warned = true; }
}
// OSSetSoundMode: `void OSSetSoundMode(u32 mode)`
void OSSetSoundMode(u32 mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: OSSetSoundMode() called\n"); warned = true; }
}
// OSSignalSemaphore: real semantics now in src/port/os_thread.cpp.
// OSSleepThread: real semantics now in src/port/os_thread.cpp.
// OSSuspendThread: real semantics now in src/port/os_thread.cpp.
// OSWaitSemaphore: real semantics now in src/port/os_thread.cpp.
// OSWakeupThread: real semantics now in src/port/os_thread.cpp.
// PCclose: `int PCclose(int fd)`
int PCclose(int fd)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PCclose() called\n"); warned = true; }
    return 0;
}
// PCcreat: `int PCcreat(const char* path, int mode)`
int PCcreat(const char* path, int mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PCcreat() called\n"); warned = true; }
    return 0;
}
// PCinit: `int PCinit()`
int PCinit()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PCinit() called\n"); warned = true; }
    return 0;
}
// PClseek: `int PClseek(int fd, int offset, int whence)`
int PClseek(int fd, int offset, int whence)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PClseek() called\n"); warned = true; }
    return 0;
}
// PCopen: `int PCopen(const char* path, int flags, int mode)`
int PCopen(const char* path, int flags, int mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PCopen() called\n"); warned = true; }
    return 0;
}
// PCread: `int PCread(int fd, void* buf, int size)`
int PCread(int fd, void* buf, int size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PCread() called\n"); warned = true; }
    return 0;
}
// PCwrite: `int PCwrite(int fd, const void* buf, int size)`
int PCwrite(int fd, const void* buf, int size)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PCwrite() called\n"); warned = true; }
    return 0;
}
// PenClothMove: `void PenClothMove(cModel* m, PenCloth* pInfo)`
void PenClothMove(cModel* m, PenCloth* pInfo)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PenClothMove() called\n"); warned = true; }
}
// PenClothMove2: `void PenClothMove2(cModel* m, PenCloth* pInfo)`
void PenClothMove2(cModel* m, PenCloth* pInfo)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PenClothMove2() called\n"); warned = true; }
}
// PenClothMove3: `void PenClothMove3(cModel* m, PenCloth* c)`
void PenClothMove3(cModel* m, PenCloth* c)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PenClothMove3() called\n"); warned = true; }
}
// PenClothSet: `void PenClothSet(cModel* m, PenCloth* pInfo, f32 min_len)`
void PenClothSet(cModel* m, PenCloth* pInfo, f32 min_len)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PenClothSet() called\n"); warned = true; }
}
// PenWindSet: `void PenWindSet(f32 dir, f32 power, f32 x)`
void PenWindSet(f32 dir, f32 power, f32 x)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PenWindSet() called\n"); warned = true; }
}
// PlGachaInit: `void PlGachaInit()`
void PlGachaInit()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlGachaInit() called\n"); warned = true; }
}
// PlGetStatus: `u32 PlGetStatus()`
u32 PlGetStatus()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlGetStatus() called\n"); warned = true; }
    return 0;
}
// PlGetWeaponNo: `int PlGetWeaponNo()`
int PlGetWeaponNo()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlGetWeaponNo() called\n"); warned = true; }
    return 0;
}
// PlIsArmor: `int PlIsArmor()`
int PlIsArmor()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlIsArmor() called\n"); warned = true; }
    return 0;
}
// PlReloadBullet: `void PlReloadBullet()`
void PlReloadBullet()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlReloadBullet() called\n"); warned = true; }
}
// UNRESOLVED: PlReloadSpeedTbl -- candidates: ['extern const f32 PlReloadSpeedTbl[45][3];', 'return PlReloadSpeedTbl[WeaponId2WeaponNo(id)][level - 1] / 30.0f;']
// PlSetDamageSe: `void PlSetDamageSe(int se_no)`
void PlSetDamageSe(int se_no)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlSetDamageSe() called\n"); warned = true; }
}
// PlSetEyeMode: `void PlSetEyeMode(u8 mode)`
void PlSetEyeMode(u8 mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlSetEyeMode() called\n"); warned = true; }
}
// UNRESOLVED: PlShotFrameTbl -- candidates: ['u8 weapon_lv_speed;', 'extern const f32 PlShotFrameTbl[45][5];']
// PlWaterProc: `void PlWaterProc(cPlayer* pEm)`
void PlWaterProc(cPlayer* pEm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlWaterProc() called\n"); warned = true; }
}
// PlWepHitCheck3: `u32 PlWepHitCheck3(Vec* pos, int type, u32 prio, f32 len)`
u32 PlWepHitCheck3(Vec* pos, int type, u32 prio, f32 len)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PlWepHitCheck3() called\n"); warned = true; }
    return 0;
}
// PPCMfpmc1: `u32 PPCMfpmc1()`
u32 PPCMfpmc1()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMfpmc1() called\n"); warned = true; }
    return 0;
}
// PPCMtmmcr0: `void PPCMtmmcr0(u32 newMmcr0)`
void PPCMtmmcr0(u32 newMmcr0)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtmmcr0() called\n"); warned = true; }
}
// PPCMtmmcr1: `void PPCMtmmcr1(u32 newMmcr0)`
void PPCMtmmcr1(u32 newMmcr0)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtmmcr1() called\n"); warned = true; }
}
// PPCMtmsr: `void PPCMtmsr(u32 newMSR)`
void PPCMtmsr(u32 newMSR)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtmsr() called\n"); warned = true; }
}
// PPCMtpmc1: `void PPCMtpmc1(u32 newPmc1)`
void PPCMtpmc1(u32 newPmc1)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtpmc1() called\n"); warned = true; }
}
// PPCMtpmc2: `void PPCMtpmc2(u32 newPmc1)`
void PPCMtpmc2(u32 newPmc1)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtpmc2() called\n"); warned = true; }
}
// PPCMtpmc3: `void PPCMtpmc3(u32 newPmc1)`
void PPCMtpmc3(u32 newPmc1)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtpmc3() called\n"); warned = true; }
}
// PPCMtpmc4: `void PPCMtpmc4(u32 newPmc1)`
void PPCMtpmc4(u32 newPmc1)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCMtpmc4() called\n"); warned = true; }
}
// PPCSync: `void PPCSync()`
void PPCSync()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PPCSync() called\n"); warned = true; }
}
// primFree: `void primFree()`
void primFree()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: primFree() called\n"); warned = true; }
}
// primInit: `void primInit()`
void primInit()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: primInit() called\n"); warned = true; }
}
// The whole PSMTX*/PSVEC* family below is NOT logging-only anymore (docs/port-boot.md's stub
// audit, coordinator lead): these are pure paired-single matrix/vector math with no hardware
// dependency (Aurora only implements the scalar C_MTX* family, docs/port-boot.md section 7 --
// none of that is wired up here, this is a plain, independent re-implementation using the same
// well-known Dolphin SDK formulas), and every caller reads the output matrix/vector afterward --
// leaving them untouched (the generic generated-stub shape) is the exact same class of bug as
// memclr_asm/OSInitSemaphore above, just for float matrices instead of raw bytes. `Mtx` is the
// GameCube's 3x4 affine transform (rows 0-2, a 4th row of [0,0,0,1] is always implicit, never
// stored).
// PSMTX44MultVec: `void PSMTX44MultVec(const Mtx44 m, const Vec* src, Vec* dst)`
// Full 4x4 * homogeneous point (w=1), no perspective divide (matches the un-normalized shape of
// every other PSMTXMultVec* here) -- **TO VERIFY** if any caller expects the divide-by-w a
// projection matrix would need instead.
void PSMTX44MultVec(const Mtx44 m, const Vec* src, Vec* dst)
{
    if (!m || !src || !dst) {
        return;
    }
    f32 x = m[0][0] * src->x + m[0][1] * src->y + m[0][2] * src->z + m[0][3];
    f32 y = m[1][0] * src->x + m[1][1] * src->y + m[1][2] * src->z + m[1][3];
    f32 z = m[2][0] * src->x + m[2][1] * src->y + m[2][2] * src->z + m[2][3];
    dst->x = x;
    dst->y = y;
    dst->z = z;
}
// PSMTXConcat: `void PSMTXConcat(const Mtx lhs, const Mtx rhs, Mtx ab)`
// ab = lhs * rhs (both 3x4 affine, implicit [0,0,0,1] 4th row) -- computed into a local temp first
// so `ab` aliasing `lhs`/`rhs` (a very common call shape, `PSMTXConcat(m, m, m)`) is safe.
void PSMTXConcat(const Mtx lhs, const Mtx rhs, Mtx ab)
{
    if (!lhs || !rhs || !ab) {
        return;
    }
    Mtx tmp;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            tmp[i][j] = lhs[i][0] * rhs[0][j] + lhs[i][1] * rhs[1][j] + lhs[i][2] * rhs[2][j];
        }
        tmp[i][3] = lhs[i][0] * rhs[0][3] + lhs[i][1] * rhs[1][3] + lhs[i][2] * rhs[2][3] + lhs[i][3];
    }
    std::memcpy(ab, tmp, sizeof(Mtx));
}
// PSMTXCopy: `void PSMTXCopy(const Mtx src, Mtx dst)`
void PSMTXCopy(const Mtx src, Mtx dst)
{
    if (src && dst && src != dst) {
        std::memcpy(dst, src, sizeof(Mtx));
    }
}
// PSMTXIdentity: `void PSMTXIdentity(Mtx m)`
void PSMTXIdentity(Mtx m)
{
    if (!m) {
        return;
    }
    m[0][0] = 1.0f; m[0][1] = 0.0f; m[0][2] = 0.0f; m[0][3] = 0.0f;
    m[1][0] = 0.0f; m[1][1] = 1.0f; m[1][2] = 0.0f; m[1][3] = 0.0f;
    m[2][0] = 0.0f; m[2][1] = 0.0f; m[2][2] = 1.0f; m[2][3] = 0.0f;
}
// PSMTXInverse: `u32 PSMTXInverse(const Mtx src, Mtx inv)`
// General affine inverse: invert the 3x3 linear part (cofactor/adjugate over the determinant),
// then invTranslation = -invRotation * translation. Returns 0 (matching the real SDK's "singular,
// did not write `inv`" contract) when the determinant is too close to zero to invert safely.
u32 PSMTXInverse(const Mtx src, Mtx inv)
{
    if (!src || !inv) {
        return 0;
    }
    f32 a = src[0][0], b = src[0][1], c = src[0][2];
    f32 d = src[1][0], e = src[1][1], f = src[1][2];
    f32 g = src[2][0], h = src[2][1], i = src[2][2];
    f32 det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g);
    if (det > -1e-12f && det < 1e-12f) {
        return 0;
    }
    f32 invDet = 1.0f / det;
    f32 r00 = (e * i - f * h) * invDet, r01 = (c * h - b * i) * invDet, r02 = (b * f - c * e) * invDet;
    f32 r10 = (f * g - d * i) * invDet, r11 = (a * i - c * g) * invDet, r12 = (c * d - a * f) * invDet;
    f32 r20 = (d * h - e * g) * invDet, r21 = (b * g - a * h) * invDet, r22 = (a * e - b * d) * invDet;
    f32 tx = src[0][3], ty = src[1][3], tz = src[2][3];
    inv[0][0] = r00; inv[0][1] = r01; inv[0][2] = r02;
    inv[1][0] = r10; inv[1][1] = r11; inv[1][2] = r12;
    inv[2][0] = r20; inv[2][1] = r21; inv[2][2] = r22;
    inv[0][3] = -(r00 * tx + r01 * ty + r02 * tz);
    inv[1][3] = -(r10 * tx + r11 * ty + r12 * tz);
    inv[2][3] = -(r20 * tx + r21 * ty + r22 * tz);
    return 1;
}
// PSMTXMultVec: `void PSMTXMultVec(const Mtx m, const Vec* src, Vec* dst)`
// Affine point transform (rotation/scale + translation); safe for `dst == src` via locals.
void PSMTXMultVec(const Mtx m, const Vec* src, Vec* dst)
{
    if (!m || !src || !dst) {
        return;
    }
    f32 x = m[0][0] * src->x + m[0][1] * src->y + m[0][2] * src->z + m[0][3];
    f32 y = m[1][0] * src->x + m[1][1] * src->y + m[1][2] * src->z + m[1][3];
    f32 z = m[2][0] * src->x + m[2][1] * src->y + m[2][2] * src->z + m[2][3];
    dst->x = x;
    dst->y = y;
    dst->z = z;
}
// PSMTXMultVecArray: `void PSMTXMultVecArray(const Mtx m, const Vec* srcBase, Vec* dstBase, u32 count)`
void PSMTXMultVecArray(const Mtx m, const Vec* srcBase, Vec* dstBase, u32 count)
{
    if (!m || !srcBase || !dstBase) {
        return;
    }
    for (u32 i = 0; i < count; i++) {
        PSMTXMultVec(m, &srcBase[i], &dstBase[i]);
    }
}
// PSMTXMultVecSR: `void PSMTXMultVecSR(const Mtx m, const Vec* src, Vec* dst)`
// Same as PSMTXMultVec but drops the translation column ("SR" = scale/rotate only) -- used for
// direction vectors, not points.
void PSMTXMultVecSR(const Mtx m, const Vec* src, Vec* dst)
{
    if (!m || !src || !dst) {
        return;
    }
    f32 x = m[0][0] * src->x + m[0][1] * src->y + m[0][2] * src->z;
    f32 y = m[1][0] * src->x + m[1][1] * src->y + m[1][2] * src->z;
    f32 z = m[2][0] * src->x + m[2][1] * src->y + m[2][2] * src->z;
    dst->x = x;
    dst->y = y;
    dst->z = z;
}
// PSMTXQuat: `void PSMTXQuat(Mtx m, const Quaternion* q)`
// Found `Quaternion`'s real layout after all (`include/vec.h`, plain x/y/z/w) -- standard
// quaternion-to-rotation-matrix formula, translation column 0.
void PSMTXQuat(Mtx m, const Quaternion* q)
{
    if (!m || !q) {
        return;
    }
    f32 x = q->x, y = q->y, z = q->z, w = q->w;
    f32 xx = x * x, yy = y * y, zz = z * z;
    f32 xy = x * y, xz = x * z, yz = y * z;
    f32 wx = w * x, wy = w * y, wz = w * z;
    m[0][0] = 1.0f - 2.0f * (yy + zz); m[0][1] = 2.0f * (xy - wz);        m[0][2] = 2.0f * (xz + wy);        m[0][3] = 0.0f;
    m[1][0] = 2.0f * (xy + wz);        m[1][1] = 1.0f - 2.0f * (xx + zz); m[1][2] = 2.0f * (yz - wx);        m[1][3] = 0.0f;
    m[2][0] = 2.0f * (xz - wy);        m[2][1] = 2.0f * (yz + wx);        m[2][2] = 1.0f - 2.0f * (xx + yy); m[2][3] = 0.0f;
}
// PSMTXRotAxisRad: `void PSMTXRotAxisRad(Mtx m, const Vec* axis, f32 rad)`
// Rodrigues' rotation formula about an arbitrary (normalized) axis; translation column left 0.
void PSMTXRotAxisRad(Mtx m, const Vec* axis, f32 rad)
{
    if (!m || !axis) {
        return;
    }
    f32 len = std::sqrt(axis->x * axis->x + axis->y * axis->y + axis->z * axis->z);
    if (len < 1e-12f) {
        PSMTXIdentity(m);
        return;
    }
    f32 x = axis->x / len, y = axis->y / len, z = axis->z / len;
    f32 c = std::cos(rad), s = std::sin(rad), t = 1.0f - c;
    m[0][0] = t * x * x + c;     m[0][1] = t * x * y - s * z; m[0][2] = t * x * z + s * y; m[0][3] = 0.0f;
    m[1][0] = t * x * y + s * z; m[1][1] = t * y * y + c;     m[1][2] = t * y * z - s * x; m[1][3] = 0.0f;
    m[2][0] = t * x * z - s * y; m[2][1] = t * y * z + s * x; m[2][2] = t * z * z + c;     m[2][3] = 0.0f;
}
// PSMTXRotRad: `void PSMTXRotRad(Mtx m, char axis, f32 rad)`
// Rotation about a cardinal axis ('X'/'Y'/'Z', either case); translation column 0.
void PSMTXRotRad(Mtx m, char axis, f32 rad)
{
    if (!m) {
        return;
    }
    f32 c = std::cos(rad), s = std::sin(rad);
    PSMTXIdentity(m);
    switch (axis) {
    case 'x': case 'X':
        m[1][1] = c;  m[1][2] = -s;
        m[2][1] = s;  m[2][2] = c;
        break;
    case 'y': case 'Y':
        m[0][0] = c;  m[0][2] = s;
        m[2][0] = -s; m[2][2] = c;
        break;
    case 'z': case 'Z':
        m[0][0] = c;  m[0][1] = -s;
        m[1][0] = s;  m[1][1] = c;
        break;
    }
}
// PSMTXScale: `void PSMTXScale(Mtx m, f32 xS, f32 yS, f32 zS)`
void PSMTXScale(Mtx m, f32 xS, f32 yS, f32 zS)
{
    if (!m) {
        return;
    }
    m[0][0] = xS;   m[0][1] = 0.0f; m[0][2] = 0.0f; m[0][3] = 0.0f;
    m[1][0] = 0.0f; m[1][1] = yS;   m[1][2] = 0.0f; m[1][3] = 0.0f;
    m[2][0] = 0.0f; m[2][1] = 0.0f; m[2][2] = zS;   m[2][3] = 0.0f;
}
// PSMTXTrans: `void PSMTXTrans(Mtx m, f32 xT, f32 yT, f32 zT)`
void PSMTXTrans(Mtx m, f32 xT, f32 yT, f32 zT)
{
    if (!m) {
        return;
    }
    m[0][0] = 1.0f; m[0][1] = 0.0f; m[0][2] = 0.0f; m[0][3] = xT;
    m[1][0] = 0.0f; m[1][1] = 1.0f; m[1][2] = 0.0f; m[1][3] = yT;
    m[2][0] = 0.0f; m[2][1] = 0.0f; m[2][2] = 1.0f; m[2][3] = zT;
}
// PSMTXTransApply: `void PSMTXTransApply(const Mtx src, Mtx dst, f32 xT, f32 yT, f32 zT)`
// dst = src with an additional translation applied in src's own (local) orientation -- i.e. the
// rotation/scale part is unchanged, the translation column gains `src`'s rotated (xT,yT,zT).
void PSMTXTransApply(const Mtx src, Mtx dst, f32 xT, f32 yT, f32 zT)
{
    if (!src || !dst) {
        return;
    }
    f32 t0 = src[0][0] * xT + src[0][1] * yT + src[0][2] * zT + src[0][3];
    f32 t1 = src[1][0] * xT + src[1][1] * yT + src[1][2] * zT + src[1][3];
    f32 t2 = src[2][0] * xT + src[2][1] * yT + src[2][2] * zT + src[2][3];
    if (src != dst) {
        std::memcpy(dst, src, sizeof(Mtx));
    }
    dst[0][3] = t0;
    dst[1][3] = t1;
    dst[2][3] = t2;
}
// PSMTXTranspose: `void PSMTXTranspose(const Mtx src, Mtx xPose)`
// Transposes the 3x3 linear part and folds the translation through it negated -- the real SDK
// semantic (matches known public decompilations), correct as an inverse for an orthonormal
// (pure rotation + translation, no scale) `src`; not a general algebraic transpose of the 3x4.
void PSMTXTranspose(const Mtx src, Mtx xPose)
{
    if (!src || !xPose) {
        return;
    }
    Mtx tmp;
    tmp[0][0] = src[0][0]; tmp[0][1] = src[1][0]; tmp[0][2] = src[2][0];
    tmp[1][0] = src[0][1]; tmp[1][1] = src[1][1]; tmp[1][2] = src[2][1];
    tmp[2][0] = src[0][2]; tmp[2][1] = src[1][2]; tmp[2][2] = src[2][2];
    tmp[0][3] = -(src[0][0] * src[0][3] + src[1][0] * src[1][3] + src[2][0] * src[2][3]);
    tmp[1][3] = -(src[0][1] * src[0][3] + src[1][1] * src[1][3] + src[2][1] * src[2][3]);
    tmp[2][3] = -(src[0][2] * src[0][3] + src[1][2] * src[1][3] + src[2][2] * src[2][3]);
    std::memcpy(xPose, tmp, sizeof(Mtx));
}
// PSVECAdd: `void PSVECAdd(const Vec* a, const Vec* b, Vec* ab)`
void PSVECAdd(const Vec* a, const Vec* b, Vec* ab)
{
    if (!a || !b || !ab) {
        return;
    }
    ab->x = a->x + b->x;
    ab->y = a->y + b->y;
    ab->z = a->z + b->z;
}
// PSVECCrossProduct: `void PSVECCrossProduct(const Vec* a, const Vec* b, Vec* axb)`
void PSVECCrossProduct(const Vec* a, const Vec* b, Vec* axb)
{
    if (!a || !b || !axb) {
        return;
    }
    f32 x = a->y * b->z - a->z * b->y;
    f32 y = a->z * b->x - a->x * b->z;
    f32 z = a->x * b->y - a->y * b->x;
    axb->x = x;
    axb->y = y;
    axb->z = z;
}
// PSVECDotProduct: `f32 PSVECDotProduct(const Vec* a, const Vec* b)`
f32 PSVECDotProduct(const Vec* a, const Vec* b)
{
    if (!a || !b) {
        return 0.0f;
    }
    return a->x * b->x + a->y * b->y + a->z * b->z;
}
// PSVECScale: `void PSVECScale(const Vec* src, Vec* dst, f32 scale)`
void PSVECScale(const Vec* src, Vec* dst, f32 scale)
{
    if (!src || !dst) {
        return;
    }
    dst->x = src->x * scale;
    dst->y = src->y * scale;
    dst->z = src->z * scale;
}
// PSVECSubtract: `void PSVECSubtract(const Vec* a, const Vec* b, Vec* a_b)`
void PSVECSubtract(const Vec* a, const Vec* b, Vec* a_b)
{
    if (!a || !b || !a_b) {
        return;
    }
    a_b->x = a->x - b->x;
    a_b->y = a->y - b->y;
    a_b->z = a->z - b->z;
}
// PullCloth: `int PullCloth(Cloth** ppCl)`
int PullCloth(Cloth** ppCl)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: PullCloth() called\n"); warned = true; }
    return 0;
}
// ReleasePlData / ReleaseWepData: real definitions now in src/game/read.cpp (docs/port-boot.md
// section 35 continuation -- read.cpp un-excluded).
// Render: `void Render()`
void Render()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Render() called\n"); warned = true; }
}
// RotMatrixZXY: `void RotMatrixZXY(Mtx m, Vec* vec)`
void RotMatrixZXY(Mtx m, Vec* vec)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: RotMatrixZXY() called\n"); warned = true; }
}
// SceAtCancelItemAt: `void SceAtCancelItemAt(cEm* pEm)`
void SceAtCancelItemAt(cEm* pEm)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtCancelItemAt() called\n"); warned = true; }
}
// SceAtCheckFieldInfo: `SceAtField* SceAtCheckFieldInfo(Vec* pos)`
SceAtField* SceAtCheckFieldInfo(Vec* pos)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtCheckFieldInfo() called\n"); warned = true; }
    return (SceAtField*) 0;
}
// SceAtCheckLadder: `int SceAtCheckLadder(cModel* pEm, Vec* pos, f32* ladder_ang, u8* ladder_height)`
int SceAtCheckLadder(cModel* pEm, Vec* pos, f32* ladder_ang, u8* ladder_height)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtCheckLadder() called\n"); warned = true; }
    return 0;
}
// SceAtCheckSystemItemSet: `int SceAtCheckSystemItemSet(u32 id, int* outId, int* outNum, Vec* pos, Vec* rot)`
int SceAtCheckSystemItemSet(u32 id, int* outId, int* outNum, Vec* pos, Vec* rot)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtCheckSystemItemSet() called\n"); warned = true; }
    return 0;
}
// SceAtCreateFieldAt: `int SceAtCreateFieldAt(cModel* m, Vec* pos, int a, int b, int c, f32 h, int d, f32 ang, int e, f32 range, int val, SceAtField** out)`
int SceAtCreateFieldAt(cModel* m, Vec* pos, int a, int b, int c, f32 h, int d, f32 ang, int e, f32 range, int val, SceAtField** out)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtCreateFieldAt() called\n"); warned = true; }
    return 0;
}
// SceAtCreateItemAt: `int SceAtCreateItemAt(Vec* pos, ITEM_ID id, int num, int effType, int saveNo, cModel* parent, int parts)`
int SceAtCreateItemAt(Vec* pos, ITEM_ID id, int num, int effType, int saveNo, cModel* parent, int parts)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtCreateItemAt() called\n"); warned = true; }
    return 0;
}
// SceAtDestroy: `int SceAtDestroy(int at_no)`
int SceAtDestroy(int at_no)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtDestroy() called\n"); warned = true; }
    return 0;
}
// SceAtItemFlgCk: `int SceAtItemFlgCk(u16 item_flg, u16 saveFlagNo)`
int SceAtItemFlgCk(u16 item_flg, u16 saveFlagNo)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtItemFlgCk() called\n"); warned = true; }
    return 0;
}
// SceAtItemFlgOn: `void SceAtItemFlgOn(u16 item_flg, u16 saveFlagNo)`
void SceAtItemFlgOn(u16 item_flg, u16 saveFlagNo)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtItemFlgOn() called\n"); warned = true; }
}
// SceAtReserveItemAt: `void SceAtReserveItemAt(cEm* pEm, Vec* pos, ITEM_ID item_id, int item_num, int item_eff, int save_no)`
void SceAtReserveItemAt(cEm* pEm, Vec* pos, ITEM_ID item_id, int item_num, int item_eff, int save_no)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceAtReserveItemAt() called\n"); warned = true; }
}
// SceCheckEventStart: `int SceCheckEventStart()`
int SceCheckEventStart()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceCheckEventStart() called\n"); warned = true; }
    return 0;
}
// SceEventEnd: `void SceEventEnd(int mode)`
void SceEventEnd(int mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceEventEnd() called\n"); warned = true; }
}
// SceEventStart: `void SceEventStart(int mode)`
void SceEventStart(int mode)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceEventStart() called\n"); warned = true; }
}
// SceMesSet: `void SceMesSet(int no, u32 flags, int sel, int x, int y)`
void SceMesSet(int no, u32 flags, int sel, int x, int y)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceMesSet() called\n"); warned = true; }
}
// SceSleep: `void SceSleep(int frames)`
void SceSleep(int frames)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SceSleep() called\n"); warned = true; }
}
// SEQInit: `void SEQInit(void)`
void SEQInit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SEQInit() called\n"); warned = true; }
}
// SEQQuit: `void SEQQuit(void)`
void SEQQuit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SEQQuit() called\n"); warned = true; }
}
// SEQRunAudioFrame: `void SEQRunAudioFrame(void)`
void SEQRunAudioFrame(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SEQRunAudioFrame() called\n"); warned = true; }
}
// SetFree: `void SetFree(int no, u32 val)`
void SetFree(int no, u32 val)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SetFree() called\n"); warned = true; }
}
// SetOrientationZX: `void SetOrientationZX(Vec* z, Vec* x, Mtx m)`
void SetOrientationZX(Vec* z, Vec* x, Mtx m)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SetOrientationZX() called\n"); warned = true; }
}
// SetOrientationZY: `void SetOrientationZY(Vec* z, Vec* y, Mtx m)`
void SetOrientationZY(Vec* z, Vec* y, Mtx m)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SetOrientationZY() called\n"); warned = true; }
}
// UNRESOLVED: SetPlDamage -- candidates: ['void SetPlDamage(cEm* em, void (*func)(cPlayer*));', 'cEm* pEmCatch;']
// SetPrimBuffPtr: `void SetPrimBuffPtr()`
void SetPrimBuffPtr()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SetPrimBuffPtr() called\n"); warned = true; }
}
// UNRESOLVED: SetSubBulldozer -- candidates: ['void SetSubBulldozer(void (*ft)(cEm*), void (*ftdm)(cEm*));', 'void (*pAux)(cEm*);']
// ShadowInit: `void ShadowInit()`
void ShadowInit()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ShadowInit() called\n"); warned = true; }
}
// ShadowMemClear: `void ShadowMemClear()`
void ShadowMemClear()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ShadowMemClear() called\n"); warned = true; }
}
// ShapeMove: `int ShapeMove(cModelInfo* i_pModelInfo)`
int ShapeMove(cModelInfo* i_pModelInfo)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: ShapeMove() called\n"); warned = true; }
    return 0;
}
// SINF: `f32 SINF(f32 x)`
f32 SINF(f32 x)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SINF() called\n"); warned = true; }
    return 0.0f;
}
// SQRTF: `f32 SQRTF(f32 x)`
f32 SQRTF(f32 x)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SQRTF() called\n"); warned = true; }
    return 0.0f;
}
// SubCharCheckHealing: `int SubCharCheckHealing()`
int SubCharCheckHealing()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SubCharCheckHealing() called\n"); warned = true; }
    return 0;
}
// SubCharCtrl: `void SubCharCtrl(int mode, int sccf)`
void SubCharCtrl(int mode, int sccf)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SubCharCtrl() called\n"); warned = true; }
}
// SYNGetActiveNotes: `u32 SYNGetActiveNotes(SYNSYNTH* synth)`
u32 SYNGetActiveNotes(SYNSYNTH* synth)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNGetActiveNotes() called\n"); warned = true; }
    return 0;
}
// SYNInit: `void SYNInit(void)`
void SYNInit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNInit() called\n"); warned = true; }
}
// SYNInitSynth: `void SYNInitSynth(SYNSYNTH* synth, void* wavetable, u32 aramBase, u32 zeroBase, u32 priorityVoiceAlloc, u32 priorityNoteOn, u32 priorityNoteRelease)`
void SYNInitSynth(SYNSYNTH* synth, void* wavetable, u32 aramBase, u32 zeroBase, u32 priorityVoiceAlloc, u32 priorityNoteOn, u32 priorityNoteRelease)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNInitSynth() called\n"); warned = true; }
}
// SYNMidiInput: `void SYNMidiInput(SYNSYNTH* synth, u8* input)`
void SYNMidiInput(SYNSYNTH* synth, u8* input)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNMidiInput() called\n"); warned = true; }
}
// SYNQuit: `void SYNQuit(void)`
void SYNQuit(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNQuit() called\n"); warned = true; }
}
// SYNQuitSynth: `void SYNQuitSynth(SYNSYNTH* synth)`
void SYNQuitSynth(SYNSYNTH* synth)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNQuitSynth() called\n"); warned = true; }
}
// SYNRunAudioFrame: `void SYNRunAudioFrame(void)`
void SYNRunAudioFrame(void)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNRunAudioFrame() called\n"); warned = true; }
}
// SYNSetMasterVolume: `void SYNSetMasterVolume(SYNSYNTH* synth, s32 dB)`
void SYNSetMasterVolume(SYNSYNTH* synth, s32 dB)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: SYNSetMasterVolume() called\n"); warned = true; }
}
// TEXGet: `TEXDescriptor* TEXGet(TEXPalette* pal, u32 id)`
TEXDescriptor* TEXGet(TEXPalette* pal, u32 id)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: TEXGet() called\n"); warned = true; }
    return (TEXDescriptor*) 0;
}
// Trans: `void Trans()`
void Trans()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Trans() called\n"); warned = true; }
}
// VecAngle: `f32 VecAngle(Vec* vec_a, Vec* vec_b)`
f32 VecAngle(Vec* vec_a, Vec* vec_b)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: VecAngle() called\n"); warned = true; }
    return 0.0f;
}
// VecElevation: `f32 VecElevation(Vec* v)`
f32 VecElevation(Vec* v)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: VecElevation() called\n"); warned = true; }
    return 0.0f;
}
// VecLinearCombination: `void VecLinearCombination(Vec* a, f32 c0, Vec* b, f32 c1, Vec* vec)`
void VecLinearCombination(Vec* a, f32 c0, Vec* b, f32 c1, Vec* vec)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: VecLinearCombination() called\n"); warned = true; }
}
// VecRadLimit: `void VecRadLimit(Vec* v)`
void VecRadLimit(Vec* v)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: VecRadLimit() called\n"); warned = true; }
}
// VIGetDTVStatus: `u32 VIGetDTVStatus()`
u32 VIGetDTVStatus()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: VIGetDTVStatus() called\n"); warned = true; }
    return 0;
}
// VISetPostRetraceCallback/VIWaitForRetrace: real implementations, src/port/vi.cpp
// (docs/port-boot.md's frame-presentation milestone -- these are no longer logging stubs).
// YarareAdd: `void YarareAdd(cEm* pEm, YARARE_INFO* pAt, f32 x, f32 y, f32 z, f32 r, f32 h, s16 pno, u16 flag)`
void YarareAdd(cEm* pEm, YARARE_INFO* pAt, f32 x, f32 y, f32 z, f32 r, f32 h, s16 pno, u16 flag)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: YarareAdd() called\n"); warned = true; }
}
// YarareAddCube: `void YarareAddCube(cEm* em, YARARE_INFO* box, f32 x, f32 y, f32 z, f32 w, f32 h, f32 extent, s16 no, u16 flags)`
void YarareAddCube(cEm* em, YARARE_INFO* box, f32 x, f32 y, f32 z, f32 w, f32 h, f32 extent, s16 no, u16 flags)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: YarareAddCube() called\n"); warned = true; }
}
// YarareInit: `void YarareInit(cEm* pEm, f32 x, f32 y, f32 z, f32 r, f32 h, s16 pno, u16 flag)`
void YarareInit(cEm* pEm, f32 x, f32 y, f32 z, f32 r, f32 h, s16 pno, u16 flag)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: YarareInit() called\n"); warned = true; }
}
// YarareInitCube: `void YarareInitCube(cEm* em, f32 x, f32 y, f32 z, f32 w, f32 h, f32 extent, s16 no, u16 flags)`
void YarareInitCube(cEm* em, f32 x, f32 y, f32 z, f32 w, f32 h, f32 extent, s16 no, u16 flags)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: YarareInitCube() called\n"); warned = true; }
}
// yz2Decode_Decode: `void yz2Decode_Decode(void* ctx, void* dst, u32 size, void* ev)`
void yz2Decode_Decode(void* ctx, void* dst, u32 size, void* ev)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: yz2Decode_Decode() called\n"); warned = true; }
}
} // extern "C"

// Data symbols (plain C++ linkage -- see the comment above `c_data_out` in this script).
// ActBtn: `extern cActionButton ActBtn;`
cActionButton ActBtn{};
// aniso: `extern u32 aniso;`
u32 aniso{};
// CamDbg: `extern debugCamera CamDbg;`
debugCamera CamDbg{};
// DC: `extern cDataCtrl DC;`
cDataCtrl DC{};
// EmReadModule: now defined for real by src/game/read.cpp (docs/port-boot.md section 35
// continuation -- no longer excluded), removed from here to avoid a duplicate-symbol link error.
// g_at2_cnt: `extern u32 g_at2_cnt[];`
u32 g_at2_cnt[] = {};
// g_at2_cyc: `extern u32 g_at2_cyc[];`
u32 g_at2_cyc[] = {};
// g_at2_total: `extern u32 g_at2_total;`
u32 g_at2_total{};
// g_at2_total_cyc: `extern u32 g_at2_total_cyc;`
u32 g_at2_total_cyc{};
// g_Get_tex_obj: `extern GXTexObj g_Get_tex_obj;`
GXTexObj g_Get_tex_obj{};
// GameSave: `extern cGameSave GameSave;`
cGameSave GameSave{};
// gxCsScale: `extern u8 gxCsScale[];`
u8 gxCsScale[] = {};
// lockCtr: `extern u8 lockCtr;`
u8 lockCtr{};
// lod_bias: `extern f32 lod_bias;`
f32 lod_bias{};
// m3r: `extern f32 m3r[3];`
f32 m3r[3] = {};
// max_lod: `extern u8 max_lod;`
u8 max_lod{};
// mercId: `extern MercID mercId;`
MercID mercId{};
// min_lod: `extern u8 min_lod;`
u8 min_lod{};
// PlReadModule: now defined for real by src/game/read.cpp (docs/port-boot.md section 35
// continuation -- no longer excluded), removed from here to avoid a duplicate-symbol link error.
// pSaveData: `extern SAVE_DATA_HEAD* pSaveData;`
SAVE_DATA_HEAD* pSaveData{};
// Rmode, ScreenShotTriggerType: now defined for real by src/game/main_sub.cpp (docs/port-boot.md
// section 26 -- no longer excluded), removed from here to avoid a duplicate-symbol link error.
// ThermoTlut: `extern GXTlutObj ThermoTlut;`
GXTlutObj ThermoTlut{};
// WepReadModule: now defined for real by src/game/read.cpp (docs/port-boot.md section 35
// continuation -- no longer excluded), removed from here to avoid a duplicate-symbol link error.
#endif // TARGET_PC
