// AUTO-GENERATED by tools/port/gen_boot_stubs.py -- spot-check before trusting.
#ifdef TARGET_PC
#include "stub_common.h"

// REMOVED (real definition now compiled elsewhere): BlockCreate(int, cSmd*)
// REMOVED (real definition now compiled elsewhere): BlockDestroy(int)
// REMOVED (real definition now compiled elsewhere): cActionButton::set(int, int, void*, void*, int, int, int, int)
// REMOVED (real definition now compiled elsewhere): CameraDebugInformation()
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::bindAreaCamera(CameraAreaRec*)
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::bindDefaultCamera()
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::init()
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::move()
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::offsetCorrection()
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::setAreaData(CameraCut*)
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::setBlendCount(int)
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::setBlendData(void*, void*)
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::setFloorRatio(float)
// REMOVED (real definition now compiled elsewhere): CameraQuasiFPS::setPlayerLocation(float (*) [4], Vec*)
// REMOVED (real definition now compiled elsewhere): cDataCtrl::check()
// REMOVED (real definition now compiled elsewhere): cDataCtrl::dispDebug()
// REMOVED (real definition now compiled elsewhere): cDataCtrl::getAramFree(unsigned int)
// REMOVED (real definition now compiled elsewhere): cDataCtrl::init()
// REMOVED (real definition now compiled elsewhere): cDataCtrl::setData(char*)
// REMOVED (real definition now compiled elsewhere): cDataUnit::getCommand()
// REMOVED (real definition now compiled elsewhere): cDataUnit::getCondition()
// REMOVED (real definition now compiled elsewhere): cDataUnit::setClear()
// REMOVED (real definition now compiled elsewhere): cDataUnit::setCommand(int, unsigned int, unsigned char)
// REMOVED (real definition now compiled elsewhere): cDataUnit::waitLoadOk()
// REMOVED (real definition now compiled elsewhere): cDataUnit::waitUseOk()
// REMOVED (real definition now compiled elsewhere): cGameSave::alloc()
// REMOVED (real definition now compiled elsewhere): cGameSave::load(SAVE_DATA_HEAD*)
// REMOVED (real definition now compiled elsewhere): cGameSave::save(SAVE_DATA_HEAD*, int)
// REMOVED (real definition now compiled elsewhere): Cloth::calcNormal()
// REMOVED (real definition now compiled elsewhere): Cloth::calcSpeed(float)
// REMOVED (real definition now compiled elsewhere): Cloth::Destroy()
// REMOVED (real definition now compiled elsewhere): Cloth::disturbance(unsigned int, unsigned int, float)
// REMOVED (real definition now compiled elsewhere): Cloth::move()
// REMOVED (real definition now compiled elsewhere): Cloth::Set(Vec, Vec, unsigned char, unsigned char, float, GXTexObj*, float, void*, float, GXTlutObj*, int)
// REMOVED (real definition now compiled elsewhere): Cloth::SetPosAng(Vec, Vec)
// cModel::isTrans() -- return type guessed from header: `int`
int cModel::isTrans()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: cModel::isTrans() called\n"); warned = true; }
    return 0;
}
// REMOVED (real definition now compiled elsewhere): cMot3::cMot3()
// REMOVED (real definition now compiled elsewhere): cMot3::move(float)
// REMOVED (real definition now compiled elsewhere): cMot3::set(cModel*, void*, void*, void*, void*, unsigned char, int, unsigned short, unsigned short)
// REMOVED (real definition now compiled elsewhere): cObjLauncher::cObjLauncher()
// REMOVED (real definition now compiled elsewhere): cObjLauncher::grip(int)
// REMOVED (real definition now compiled elsewhere): cObjLauncher::gripBack()
// REMOVED (real definition now compiled elsewhere): commonScreenMat(cModel*)
// REMOVED (real definition now compiled elsewhere): cPlAshley::cPlAshley()
// REMOVED (real definition now compiled elsewhere): cPlayer::actionSelect()
// REMOVED (real definition now compiled elsewhere): cPlayer::beginDamage()
// REMOVED (real definition now compiled elsewhere): cPlayer::checkCtrl()
// REMOVED (real definition now compiled elsewhere): cPlayer::checkEvent()
// REMOVED (real definition now compiled elsewhere): cPlayer::dmgCheck()
// REMOVED (real definition now compiled elsewhere): cPlayer::endAction(int)
// REMOVED (real definition now compiled elsewhere): cPlayer::endCamera()
// REMOVED (real definition now compiled elsewhere): cPlayer::endEvent0(unsigned int)
// REMOVED (real definition now compiled elsewhere): cPlayer::getLifeLevel()
// REMOVED (real definition now compiled elsewhere): cPlayer::keyConfig()
// REMOVED (real definition now compiled elsewhere): cPlayer::motionSet(void*, void*, void*, void*, int, int)
// REMOVED (real definition now compiled elsewhere): cPlayer::moveBinocular()
// REMOVED (real definition now compiled elsewhere): cPlayer::moveEye()
// REMOVED (real definition now compiled elsewhere): cPlayer::seqSeCtrl()
// REMOVED (real definition now compiled elsewhere): cPlayer::setDamage(unsigned char, int, float, int, int)
// REMOVED (real definition now compiled elsewhere): cPlayer::setFootwork()
// REMOVED (real definition now compiled elsewhere): cPlayer::shadowCtrl()
// cPlayer::subCharLiveCheck() -- return type guessed from header: `void`
void cPlayer::subCharLiveCheck()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: cPlayer::subCharLiveCheck() called\n"); warned = true; }
}
// REMOVED (real definition now compiled elsewhere): cPlayer::subScrCheck()
// REMOVED (real definition now compiled elsewhere): cPlayer::visibleCtrl()
// REMOVED (real definition now compiled elsewhere): cPlayer::weaponInit()
// REMOVED (real definition now compiled elsewhere): cPlayer::weaponLoad(int, int)
// REMOVED (real definition now compiled elsewhere): cPlayer::weaponRelease()
// REMOVED (real definition now compiled elsewhere): cPlLeon::cPlLeon()
// REMOVED (real definition now compiled elsewhere): cPlNeck::cPlNeck(cPlayer*)
// REMOVED (real definition now compiled elsewhere): cPlNeck::init(void*, void*, int)
// REMOVED (real definition now compiled elsewhere): cPlNeck::move()
// REMOVED (real definition now compiled elsewhere): cPlWaist::cPlWaist()
// REMOVED (real definition now compiled elsewhere): cPlWaist::set(float, float)
// REMOVED (real definition now compiled elsewhere): cPlWep::cPlWep()
// REMOVED (real definition now compiled elsewhere): cPlWep::getAngle()
// REMOVED (real definition now compiled elsewhere): cPlWep::getMarkerPos(Vec*)
// REMOVED (real definition now compiled elsewhere): cPlWep::lockMove()
// REMOVED (real definition now compiled elsewhere): cPlWep::move()
// REMOVED (real definition now compiled elsewhere): cPlWep::setTrans(int, int)
// REMOVED (real definition now compiled elsewhere): cSmd::slide(int)
// REMOVED (real definition now compiled elsewhere): debugCamera::move(Camera*, JOY*, int)
// REMOVED (real definition now compiled elsewhere): DebugTrg(int)
// REMOVED (real definition now compiled elsewhere): dmMotCk()
// Esp04_Create() -- free function, return type guessed: `cEsp*`
cEsp* Esp04_Create()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp04_Create() called\n"); warned = true; }
    return (cEsp*) 0;
}
// Esp0a_Create() -- free function, return type guessed: `cEsp*`
cEsp* Esp0a_Create()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp0a_Create() called\n"); warned = true; }
    return (cEsp*) 0;
}
// Esp12_Create() -- free function, return type guessed: `cEsp*`
cEsp* Esp12_Create()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp12_Create() called\n"); warned = true; }
    return (cEsp*) 0;
}
// Esp16_Create() -- free function, return type guessed: `cEsp*`
cEsp* Esp16_Create()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: Esp16_Create() called\n"); warned = true; }
    return (cEsp*) 0;
}
// REMOVED (real definition now compiled elsewhere): GameStopModeEnd()
// GetBugCheckController() -- free function, return type guessed: `JOY*`
JOY* GetBugCheckController()
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GetBugCheckController() called\n"); warned = true; }
    return (JOY*) 0;
}
// GetDataExt: real definition now in src/game/read.cpp (docs/port-boot.md section 35
// continuation -- read.cpp un-excluded).
// GetWaterHeight(Vec*, float*) -- free function, return type guessed: `int`
int GetWaterHeight(Vec* a0, float* a1)
{
    static bool warned = false;
    if (!warned) { std::fprintf(stderr, "STUB: GetWaterHeight() called\n"); warned = true; }
    return 0;
}
// REMOVED (real definition now compiled elsewhere): joyFireOn()
// REMOVED (real definition now compiled elsewhere): joyFireTrg()
// REMOVED (real definition now compiled elsewhere): joyKamae()
// REMOVED (real definition now compiled elsewhere): joyLKamae()
// REMOVED (real definition now compiled elsewhere): lightSetEm(cModel*)
// REMOVED (real definition now compiled elsewhere): MercID::set()
// REMOVED (real definition now compiled elsewhere): ModelRender(cModel*)
// REMOVED (real definition now compiled elsewhere): moveOnPlaneXZ(Vec*, Vec*)
// REMOVED (real definition now compiled elsewhere): PlChangeData()
// REMOVED (real definition now compiled elsewhere): PlSetCostume()
// REMOVED (real definition now compiled elsewhere): PlWepHitCheck2(cModel*, Vec*, Vec*, int, unsigned int, float)
// REMOVED (real definition now compiled elsewhere): PlWepLockCtrl(cModel*)
// Render_checkBlurPermission() now defined for real by src/game/main_sub.cpp (docs/port-boot.md
// section 26 -- no longer excluded), removed from here to avoid a duplicate-symbol link error.
// SearchEmModule: real definition now in src/game/read.cpp (docs/port-boot.md section 35
// continuation -- read.cpp un-excluded).
// REMOVED (real definition now compiled elsewhere): SetSubDamage(cEm*, void (*)())
// REMOVED (real definition now compiled elsewhere): ShapeEnd(void*)
// REMOVED (real definition now compiled elsewhere): ShapeSet(void*, int, void*, int)
// REMOVED (real definition now compiled elsewhere): SmdGetGroupObjPtr(unsigned int)
// REMOVED (real definition now compiled elsewhere): SmdGetGroupObjPtr2(unsigned int)
// REMOVED (real definition now compiled elsewhere): SmdGetObjPtr(unsigned int)
// REMOVED (real definition now compiled elsewhere): SmdGetWorkId(cObj*)
#endif // TARGET_PC
