// REL plan step 2-5 (docs/port-boot.md "REL modules, statically linked"): the descriptor a
// statically-linked REL module exposes to the (future, not wired yet -- next slice) module
// registry that will replace OSLink/OSUnlink. One `RelModuleDesc` per module, built by that
// module's own generated `desc.cpp` (tools/port/gen_rel_module.py) and reached through a single
// per-module accessor function (`<Mod>_GetModuleDesc()`, `extern "C"`, module-name-qualified so it
// never collides with another module's own copy) -- the ONLY symbol a module's combined,
// visibility-restricted object exports (see gen_rel_module.py's own header comment for the
// two-phase `ld -r` this backs).
#ifndef TARGET_PC
#error "include/port/rel_module.h is host-only (TARGET_PC)"
#endif

#ifndef RE4_PORT_REL_MODULE_H
#define RE4_PORT_REL_MODULE_H

#include <cstddef>

struct OSModuleInfo; // include/dolphin/os/OSModule.h; not included here to keep this header light

namespace re4_port {

struct RelModuleDesc {
    unsigned id;             // config/G4BE08/modules/<mod>/rel.json's module_id (OSModuleID)
    const char* name;        // rel.json's own "name" (vendor module name, e.g. "st1_0")
    void (*prolog)();        // this module's own _prolog (ctors + setTbl, src/st1/st1.cpp et al.)
    void (*epilog)();        // this module's own _epilog (dtors)
    void (*unresolved)();    // this module's own _unresolved (HALT stub for unbound imports)
    // [start, start + size) for each of the module's own GC-faithful-layout sections (custom Mach-O
    // sections generated by gen_rel_module.py's section.h, `#pragma clang section`-tagged into the
    // module's TUs). nullptr/0 if the module ended up with no data/bss/rodata content at all (a
    // legal, if unlikely, REL shape) -- not an error, mirrors src/port/arena.cpp's own
    // CheckGameSection() treating an absent section as nothing to check.
    void* dataStart;
    std::size_t dataSize;
    void* bssStart;
    std::size_t bssSize;
    void* rodataStart;
    std::size_t rodataSize;
};

} // namespace re4_port

#endif // RE4_PORT_REL_MODULE_H
